function finalDRScreening
% =========================================================================
% EXPLAINABLE AI FOR DIABETIC RETINOPATHY SCREENING
% MATLAB R2026a
%
% PAGE-BASED SCREENING APPLICATION
%
% IMPORTANT:
%   Same visual design / same color system.
%   Each analysis option opens its own page.
%
% WORKFLOW
%   New Screening
%       |
%       v
%   Upload Fundus Image
%       |
%       v
%   Analyze Retina
%       |
%       +----> Image Quality
%       |
%       +----> Retinal Structure
%       |
%       +----> Clinical Evidence
%       |
%       +----> Explainability
%       |
%       +----> Screening Result
%       |
%       +----> Clinical Report
%
% BACKEND
%   Image Quality Assessment
%   Retinal Enhancement
%   FOV Detection
%   Vessel Segmentation
%   Optic Disc Detection
%   Clinical Candidate Evidence
%   ResNet-18 Classification
%   Grad-CAM
%   Referable DR Decision
%   Screening Recommendation
%   Report Generation
%
% RESEARCH PROTOTYPE:
%   Candidate regions are algorithmic evidence only.
%   AI output does not replace ophthalmologist examination.
% =========================================================================

clc;

%% ========================================================================
% PROJECT PATHS
% ========================================================================

projectRoot = fileparts(mfilename('fullpath'));

modelFile = fullfile( ...
    projectRoot, ...
    'models', ...
    'DR_Model.mat');

resultsDir = fullfile( ...
    projectRoot, ...
    'results');

if ~isfolder(resultsDir)
    mkdir(resultsDir);
end

%% ========================================================================
% SAME COLOR SYSTEM
% ========================================================================

NAVY      = [0.035 0.12 0.21];
NAVY2     = [0.055 0.18 0.30];

BLUE      = [0.03 0.40 0.72];
BLUE2     = [0.08 0.50 0.78];

BG        = [0.94 0.96 0.98];
WHITE     = [1.00 1.00 1.00];

TEXT      = [0.055 0.12 0.19];
MUTED     = [0.25 0.33 0.42];

LIGHTBLUE = [0.60 0.78 0.94];

GREEN     = [0.02 0.50 0.25];
ORANGE    = [0.85 0.45 0.05];
RED       = [0.80 0.08 0.10];

BORDER    = [0.78 0.82 0.86];

%% ========================================================================
% STATE
% ========================================================================

state = struct();

state.image = [];

state.fileName = "";

state.processed = [];

state.retinaMask = [];

state.vesselMask = [];

state.vesselDensity = 0;

state.opticDiscDetected = false;

state.opticDiscCenter = [];

state.foveaEstimated = false;

state.foveaCenter = [];

state.qualityTotal = 0;

state.focusScore = 0;

state.illuminationScore = 0;

state.fovScore = 0;

state.contrastScore = 0;

state.qualityStatus = "PENDING";

state.brightCandidates = 0;

state.darkCandidates = 0;

state.redCandidates = 0;

state.totalCandidates = 0;

state.brightMask = [];

state.darkMask = [];

state.redMask = [];

% ========================================================================
% AI PREDICTION STATE
% ========================================================================

state.grade = "Not analyzed";
state.gradeIndex = -1;
state.confidence = 0;
state.probabilities = zeros(5,1);

% Initial value before image analysis
state.referable = false;

% Referable DR probability
state.referableProbability = 0;

% ========================================================================
% CALIBRATED REFERABLE DR THRESHOLD
% ========================================================================

% Threshold obtained from validation-set calibration
% and evaluated on the independent test set.

state.referableThreshold = 0.01;
% Referable DR probability
state.referableProbability = 0;

% ========================================================================
% EXPLAINABILITY STATE
% ========================================================================

state.attentionMap = [];

state.attentionSource = "Not generated";

% ========================================================================
% MODEL STATE
% ========================================================================

state.modelLoaded = false;

state.trainedNet = [];

state.classNames = [ ...
    "No DR", ...
    "Mild DR", ...
    "Moderate DR", ...
    "Severe DR", ...
    "Proliferative DR"];
%% ========================================================================
% LOAD TRAINED MODEL
% ========================================================================

modelFile = fullfile( ...
    projectRoot, ...
    'models', ...
    'DR_Model.mat');


if exist(modelFile,'file')

    S = load(modelFile);


    if isfield(S,'trainedNet')

        state.trainedNet = ...
            S.trainedNet;

        state.modelLoaded = true;

    else

        state.trainedNet = [];

        state.modelLoaded = false;

        error( ...
            'DR_Model.mat does not contain trainedNet.');

    end


    if isfield(S,'classNames')

        state.classNames = ...
            S.classNames;

    else

        state.classNames = ...
            ["No DR", ...
             "Mild DR", ...
             "Moderate DR", ...
             "Severe DR", ...
             "Proliferative DR"];

    end

else

    state.trainedNet = [];

    state.modelLoaded = false;

    error( ...
        'DR_Model.mat was not found in the models folder.');

end
%% ========================================================================
% MAIN FIGURE
% ========================================================================

fig = uifigure( ...
    'Name','Diabetic Retinopathy Screening', ...
    'Position',[40 40 1500 900], ...
    'Color',BG);

fig.WindowState = 'maximized';

%% ========================================================================
% ROOT LAYOUT
% ========================================================================

rootGrid = uigridlayout(fig,[1 2]);

rootGrid.ColumnWidth = {300,'1x'};
rootGrid.RowHeight = {'1x'};

rootGrid.Padding = [0 0 0 0];
rootGrid.ColumnSpacing = 0;
rootGrid.RowSpacing = 0;
rootGrid.BackgroundColor = BG;

%% ========================================================================
% SIDEBAR
% ========================================================================

sidebar = uipanel( ...
    rootGrid, ...
    'BackgroundColor',NAVY, ...
    'BorderType','none');

uilabel( ...
    sidebar, ...
    'Text','AI', ...
    'Position',[25 820 250 55], ...
    'FontSize',32, ...
    'FontWeight','bold', ...
    'FontColor',WHITE, ...
    'HorizontalAlignment','center');

uilabel( ...
    sidebar, ...
    'Text','EXPLAINABLE RETINAL SCREENING', ...
    'Position',[20 775 260 25], ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'FontColor',LIGHTBLUE, ...
    'HorizontalAlignment','center');

uilabel( ...
    sidebar, ...
    'Text','SCREENING', ...
    'Position',[25 720 250 25], ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'FontColor',LIGHTBLUE);

newButton = makeSideButton( ...
    sidebar, ...
    'New Screening', ...
    [25 660 250 55], ...
    NAVY2, ...
    @newScreening);

uploadButton = makeSideButton( ...
    sidebar, ...
    'Upload Fundus Image', ...
    [25 590 250 55], ...
    NAVY2, ...
    @uploadImage);

analyzeButton = makeSideButton( ...
    sidebar, ...
    'Analyze Retina', ...
    [25 520 250 55], ...
    BLUE2, ...
    @analyzeImage);

uilabel( ...
    sidebar, ...
    'Text','ANALYSIS', ...
    'Position',[25 470 250 25], ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'FontColor',LIGHTBLUE);

qualityButton = makeSideButton( ...
    sidebar, ...
    'Image Quality', ...
    [25 405 250 50], ...
    NAVY2, ...
    @showQuality);

structureButton = makeSideButton( ...
    sidebar, ...
    'Retinal Structure', ...
    [25 340 250 50], ...
    NAVY2, ...
    @showStructure);

evidenceButton = makeSideButton( ...
    sidebar, ...
    'Clinical Evidence', ...
    [25 275 250 50], ...
    NAVY2, ...
    @showEvidence);

explainButton = makeSideButton( ...
    sidebar, ...
    'Explainability', ...
    [25 210 250 50], ...
    NAVY2, ...
    @showExplainability);

uilabel( ...
    sidebar, ...
    'Text','RESULTS', ...
    'Position',[25 165 250 25], ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'FontColor',LIGHTBLUE);

resultButton = makeSideButton( ...
    sidebar, ...
    'Screening Result', ...
    [25 100 250 50], ...
    NAVY2, ...
    @showResult);

reportButton = makeSideButton( ...
    sidebar, ...
    'Clinical Report', ...
    [25 35 250 50], ...
    NAVY2, ...
    @showReport);

if state.modelLoaded

    modelText = '● RESNET-18 MODEL READY';
    modelColor = [0.25 1.00 0.55];

else

    modelText = '● MODEL NOT FOUND';
    modelColor = RED;

end

uilabel( ...
    sidebar, ...
    'Text',modelText, ...
    'Position',[20 -5 260 25], ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'FontColor',modelColor, ...
    'HorizontalAlignment','center');

%% ========================================================================
% RIGHT SIDE MAIN AREA
% ========================================================================

mainGrid = uigridlayout(rootGrid,[2 1]);

% KEEP THE ORIGINAL HEIGHT
mainGrid.RowHeight = {115,'1x'};

mainGrid.ColumnWidth = {'1x'};
mainGrid.Padding = [0 0 0 0];
mainGrid.RowSpacing = 0;
mainGrid.BackgroundColor = BG;

%% ========================================================================
% HEADER
% ========================================================================

header = uipanel( ...
    mainGrid, ...
    'BackgroundColor',NAVY, ...
    'BorderType','none');

% Header layout only.
% The child grid uses the SAME NAVY background.
headerGrid = uigridlayout(header,[2 2]);

headerGrid.RowHeight = {58,38};
headerGrid.ColumnWidth = {'1x',330};

headerGrid.Padding = [30 8 25 8];
headerGrid.RowSpacing = 0;
headerGrid.ColumnSpacing = 10;

headerGrid.BackgroundColor = NAVY;

%% ------------------------------------------------------------------------
% TITLE
% -------------------------------------------------------------------------

headerTitle = uilabel( ...
    headerGrid, ...
    'Text','DIABETIC RETINOPATHY SCREENING', ...
    'FontSize',25, ...
    'FontWeight','bold', ...
    'FontColor',WHITE, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','center');

headerTitle.Layout.Row = 1;
headerTitle.Layout.Column = 1;

%% ------------------------------------------------------------------------
% STATUS
% -------------------------------------------------------------------------

headerStatus = uilabel( ...
    headerGrid, ...
    'Text','● DASHBOARD', ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'FontColor',[0.25 1.00 0.55], ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','center');

headerStatus.Layout.Row = 1;
headerStatus.Layout.Column = 2;

%% ------------------------------------------------------------------------
% SUBTITLE
% -------------------------------------------------------------------------

headerSubtitle = uilabel( ...
    headerGrid, ...
    'Text','AI-ASSISTED  |  EXPLAINABLE  |  QUALITY-AWARE', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'FontColor',LIGHTBLUE, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','center');

headerSubtitle.Layout.Row = 2;
headerSubtitle.Layout.Column = 1;

%% ------------------------------------------------------------------------
% DATE
% -------------------------------------------------------------------------

headerDate = uilabel( ...
    headerGrid, ...
    'Text',char(string(datetime( ...
    'now','Format','dd MMM yyyy | HH:mm'))), ...
    'FontSize',10, ...
    'FontColor',LIGHTBLUE, ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','center');

headerDate.Layout.Row = 2;
headerDate.Layout.Column = 2;
%% ========================================================================
% PAGE CONTAINER
% ========================================================================

pageContainer = uipanel( ...
    mainGrid, ...
    'BackgroundColor',BG, ...
    'BorderType','none', ...
    'Scrollable','on');
%% ========================================================================
% CREATE PAGES
% ========================================================================

dashboardPage = uipanel( ...
    pageContainer, ...
    'Position',[0 0 1200 950], ...
    'BackgroundColor',BG, ...
    'BorderType','none');

qualityPage = uipanel( ...
    pageContainer, ...
    'Position',[0 0 1200 800], ...
    'BackgroundColor',BG, ...
    'BorderType','none', ...
    'Visible','off');

structurePage = uipanel( ...
    pageContainer, ...
    'Position',[0 0 1200 800], ...
    'BackgroundColor',BG, ...
    'BorderType','none', ...
    'Visible','off');

evidencePage = uipanel( ...
    pageContainer, ...
    'Position',[0 0 1200 800], ...
    'BackgroundColor',BG, ...
    'BorderType','none', ...
    'Visible','off');

explainPage = uipanel( ...
    pageContainer, ...
    'Position',[0 0 1200 800], ...
    'BackgroundColor',BG, ...
    'BorderType','none', ...
    'Visible','off');

resultPage = uipanel( ...
    pageContainer, ...
    'Position',[0 0 1200 800], ...
    'BackgroundColor',BG, ...
    'BorderType','none', ...
    'Visible','off');

reportPage = uipanel( ...
    pageContainer, ...
    'Position',[0 0 1200 800], ...
    'BackgroundColor',BG, ...
    'BorderType','none', ...
    'Visible','off');


%% ========================================================================
% DASHBOARD PAGE
% ========================================================================

% Dashboard status bar
dashboardStatus = uipanel( ...
    dashboardPage, ...
    'Position',[25 690 1120 55], ...
    'BackgroundColor',WHITE, ...
    'BorderType','line');

statusLabel = uilabel( ...
    dashboardStatus, ...
    'Text','● READY', ...
    'Position',[20 10 250 35], ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'FontColor',MUTED);

qualityStatusLabel = uilabel( ...
    dashboardStatus, ...
    'Text','IMAGE QUALITY: PENDING', ...
    'Position',[300 10 250 35], ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'FontColor',MUTED);

modelStatusLabel = uilabel( ...
    dashboardStatus, ...
    'Text',ternaryText( ...
        state.modelLoaded, ...
        'AI MODEL: TRAINED', ...
        'AI MODEL: NOT FOUND'), ...
    'Position',[590 10 230 35], ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'FontColor',MUTED);

decisionStatusLabel = uilabel( ...
    dashboardStatus, ...
    'Text','DECISION: PENDING', ...
    'Position',[850 10 240 35], ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'FontColor',MUTED);


uilabel( ...
    dashboardPage, ...
    'Text','AI-ASSISTED RETINAL SCREENING', ...
    'Position',[25 625 650 45], ...
    'FontSize',25, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

uilabel( ...
    dashboardPage, ...
    'Text','Upload an image and run the analysis. Results are organized into dedicated clinical review pages.', ...
    'Position',[25 595 1050 25], ...
    'FontSize',12, ...
    'FontColor',MUTED);


%% ========================================================================
% DASHBOARD IMAGE CARDS
% ========================================================================

originalCard = makeCard( ...
    dashboardPage, ...
    [20 300 300 255], ...
    'ORIGINAL FUNDUS IMAGE');

originalAxes = uiaxes( ...
    originalCard, ...
    'Position',[15 15 270 195]);

originalAxes.XTick = [];
originalAxes.YTick = [];
originalAxes.Box = 'on';

try
    originalAxes.Toolbar.Visible = 'off';
catch
end

title(originalAxes,'Upload an image');


enhancedCard = makeCard( ...
    dashboardPage, ...
    [345 300 300 255], ...
    'ENHANCED RETINAL VIEW');

enhancedAxes = uiaxes( ...
    enhancedCard, ...
    'Position',[15 15 270 195]);

enhancedAxes.XTick = [];
enhancedAxes.YTick = [];
enhancedAxes.Box = 'on';

try
    enhancedAxes.Toolbar.Visible = 'off';
catch
end

title(enhancedAxes,'Waiting for analysis');


attentionCard = makeCard( ...
    dashboardPage, ...
    [670 300 300 255], ...
    'AI ATTENTION / GRAD-CAM');

camAxes = uiaxes( ...
    attentionCard, ...
    'Position',[15 35 270 180]);

camAxes.XTick = [];
camAxes.YTick = [];
camAxes.Box = 'on';

try
    camAxes.Toolbar.Visible = 'off';
catch
end

title(camAxes,'AI attention will appear here');

camSourceLabel = uilabel( ...
    attentionCard, ...
    'Text','Attention status: pending', ...
    'Position',[15 8 270 20], ...
    'FontSize',9, ...
    'FontWeight','bold', ...
    'FontColor',MUTED, ...
    'HorizontalAlignment','center');


%% ========================================================================
% DASHBOARD RESULT
% ========================================================================

summaryCard = makeCard( ...
    dashboardPage, ...
    [25 120 1090 170], ...
    'CURRENT SCREENING STATUS');

gradeLabel = uilabel( ...
    summaryCard, ...
    'Text','GRADE —', ...
    'Position',[25 55 300 55], ...
    'FontSize',27, ...
    'FontWeight','bold', ...
    'FontColor',BLUE);

confidenceLabel = uilabel( ...
    summaryCard, ...
    'Text','CONFIDENCE: —', ...
    'Position',[350 75 220 30], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

referableLabel = uilabel( ...
    summaryCard, ...
    'Text','REFERABLE DR: —', ...
    'Position',[590 75 220 30], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

finalDecisionLabel = uilabel( ...
    summaryCard, ...
    'Text','AWAITING ANALYSIS', ...
    'Position',[820 50 245 60], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontColor',MUTED, ...
    'HorizontalAlignment','center');

pipelineLabel = uilabel( ...
    dashboardPage, ...
    'Text','Upload → Analyze → Review evidence → Validate AI result → Generate report', ...
    'Position',[25 65 1090 25], ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'FontColor',MUTED, ...
    'HorizontalAlignment','center');

%% Dashboard result

summaryCard = makeCard( ...
    dashboardPage, ...
    [25 120 1090 170], ...
    'CURRENT SCREENING STATUS');

gradeLabel = uilabel( ...
    summaryCard, ...
    'Text','GRADE —', ...
    'Position',[25 55 300 55], ...
    'FontSize',27, ...
    'FontWeight','bold', ...
    'FontColor',BLUE);

confidenceLabel = uilabel( ...
    summaryCard, ...
    'Text','CONFIDENCE: —', ...
    'Position',[350 75 220 30], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

referableLabel = uilabel( ...
    summaryCard, ...
    'Text','REFERABLE DR: —', ...
    'Position',[590 75 220 30], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

finalDecisionLabel = uilabel( ...
    summaryCard, ...
    'Text','AWAITING ANALYSIS', ...
    'Position',[820 50 245 60], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontColor',MUTED, ...
    'HorizontalAlignment','center');

pipelineLabel = uilabel( ...
    dashboardPage, ...
    'Text','Upload → Analyze → Review evidence → Validate AI result → Generate report', ...
    'Position',[25 65 1090 25], ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'FontColor',MUTED, ...
    'HorizontalAlignment','center');

%% ========================================================================
% IMAGE QUALITY PAGE
% ========================================================================

makePageTitle( ...
    qualityPage, ...
    'IMAGE QUALITY ASSESSMENT', ...
    'Assess image suitability before clinical interpretation.');

qualityBack = makeBackButton(qualityPage,@showDashboard);

qualityOriginalCard = makeCard( ...
    qualityPage, ...
    [25 365 350 280], ...
    'ORIGINAL FUNDUS IMAGE');

qualityOriginalAxes = uiaxes( ...
    qualityOriginalCard, ...
    'Position',[15 15 320 220]);

qualityOriginalAxes.XTick = [];
qualityOriginalAxes.YTick = [];

try
    qualityOriginalAxes.Toolbar.Visible = 'off';
catch
end

qualityEnhancedCard = makeCard( ...
    qualityPage, ...
    [395 365 350 280], ...
    'ENHANCED RETINAL VIEW');

qualityEnhancedAxes = uiaxes( ...
    qualityEnhancedCard, ...
    'Position',[15 15 320 220]);

qualityEnhancedAxes.XTick = [];
qualityEnhancedAxes.YTick = [];

try
    qualityEnhancedAxes.Toolbar.Visible = 'off';
catch
end

qualityMetricsCard = makeCard( ...
    qualityPage, ...
    [765 365 350 280], ...
    'QUALITY METRICS');

qualityOverall = uilabel( ...
    qualityMetricsCard, ...
    'Text','OVERALL  — / 100', ...
    'Position',[20 190 310 40], ...
    'FontSize',20, ...
    'FontWeight','bold', ...
    'FontColor',BLUE, ...
    'HorizontalAlignment','center');

qualityState = uilabel( ...
    qualityMetricsCard, ...
    'Text','PENDING', ...
    'Position',[20 155 310 30], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontColor',MUTED, ...
    'HorizontalAlignment','center');

qualityFocus = uilabel( ...
    qualityMetricsCard, ...
    'Text','Focus / Sharpness: —', ...
    'Position',[20 115 310 25], ...
    'FontSize',12, ...
    'FontColor',TEXT);

qualityIllumination = uilabel( ...
    qualityMetricsCard, ...
    'Text','Illumination: —', ...
    'Position',[20 85 310 25], ...
    'FontSize',12, ...
    'FontColor',TEXT);

qualityFOV = uilabel( ...
    qualityMetricsCard, ...
    'Text','FOV Coverage: —', ...
    'Position',[20 55 310 25], ...
    'FontSize',12, ...
    'FontColor',TEXT);

qualityContrast = uilabel( ...
    qualityMetricsCard, ...
    'Text','Contrast: —', ...
    'Position',[20 25 310 25], ...
    'FontSize',12, ...
    'FontColor',TEXT);

qualityDecisionCard = makeCard( ...
    qualityPage, ...
    [25 100 1090 220], ...
    'QUALITY GATE & RECAPTURE GUIDANCE');

qualityDecisionText = uilabel( ...
    qualityDecisionCard, ...
    'Text',{ ...
    'Upload and analyze an image to evaluate quality.'; ...
    ''; ...
    'GOOD      → suitable for screening'; ...
    'BORDERLINE → review carefully'; ...
    'POOR      → recapture recommended'}, ...
    'Position',[25 35 1040 135], ...
    'FontSize',14, ...
    'FontColor',TEXT, ...
    'WordWrap','on');

%% ========================================================================
% RETINAL STRUCTURE PAGE
% ========================================================================

makePageTitle( ...
    structurePage, ...
    'RETINAL STRUCTURE ANALYSIS', ...
    'Retinal field, vessels, optic disc and estimated foveal location.');

structureBack = makeBackButton(structurePage,@showDashboard);

structureImageCard = makeCard( ...
    structurePage, ...
    [25 325 570 340], ...
    'RETINAL STRUCTURE OVERLAY');

structureAxes = uiaxes( ...
    structureImageCard, ...
    'Position',[15 15 540 285]);

structureAxes.XTick = [];
structureAxes.YTick = [];

try
    structureAxes.Toolbar.Visible = 'off';
catch
end

title(structureAxes,'Run analysis');

structureInfoCard = makeCard( ...
    structurePage, ...
    [625 325 490 340], ...
    'STRUCTURE FINDINGS');

structureVesselLabel = uilabel( ...
    structureInfoCard, ...
    'Text','Vessel Density: —', ...
    'Position',[25 240 440 35], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

structureDiscLabel = uilabel( ...
    structureInfoCard, ...
    'Text','Optic Disc: —', ...
    'Position',[25 190 440 35], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

structureFoveaLabel = uilabel( ...
    structureInfoCard, ...
    'Text','Fovea Estimate: —', ...
    'Position',[25 140 440 35], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

structureFOVLabel = uilabel( ...
    structureInfoCard, ...
    'Text','Retinal FOV: —', ...
    'Position',[25 90 440 35], ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

structureNote = uilabel( ...
    structureInfoCard, ...
    'Text','Structure measurements are algorithmic screening features.', ...
    'Position',[25 30 440 45], ...
    'FontSize',11, ...
    'FontColor',MUTED, ...
    'WordWrap','on');

%% ========================================================================
% CLINICAL EVIDENCE PAGE
% ========================================================================

makePageTitle( ...
    evidencePage, ...
    'CLINICAL EVIDENCE', ...
    'Algorithmic candidate regions supporting the AI screening result.');

evidenceBack = makeBackButton(evidencePage,@showDashboard);

evidenceImageCard = makeCard( ...
    evidencePage, ...
    [25 325 700 340], ...
    'CANDIDATE EVIDENCE MAP');

evidenceAxes = uiaxes( ...
    evidenceImageCard, ...
    'Position',[15 15 670 285]);

evidenceAxes.XTick = [];
evidenceAxes.YTick = [];

try
    evidenceAxes.Toolbar.Visible = 'off';
catch
end

title(evidenceAxes,'Run analysis');

evidenceInfoCard = makeCard( ...
    evidencePage, ...
    [755 325 360 340], ...
    'CANDIDATE FINDINGS');

brightEvidenceLabel = uilabel( ...
    evidenceInfoCard, ...
    'Text','BRIGHT CANDIDATES: 0', ...
    'Position',[25 245 310 35], ...
    'FontSize',14, ...
    'FontWeight','bold', ...
    'FontColor',ORANGE);

darkEvidenceLabel = uilabel( ...
    evidenceInfoCard, ...
    'Text','DARK CANDIDATES: 0', ...
    'Position',[25 195 310 35], ...
    'FontSize',14, ...
    'FontWeight','bold', ...
    'FontColor',BLUE);

redEvidenceLabel = uilabel( ...
    evidenceInfoCard, ...
    'Text','RED CANDIDATES: 0', ...
    'Position',[25 145 310 35], ...
    'FontSize',14, ...
    'FontWeight','bold', ...
    'FontColor',RED);

totalEvidenceLabel = uilabel( ...
    evidenceInfoCard, ...
    'Text','TOTAL CANDIDATES: 0', ...
    'Position',[25 95 310 35], ...
    'FontSize',14, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

evidenceDisclaimer = uilabel( ...
    evidenceInfoCard, ...
    'Text',{ ...
    'Bright: exudate-like'; ...
    'Dark: microaneurysm / hemorrhage-like'; ...
    'Red: hemorrhage-like'; ...
    ''; ...
    'These are candidate regions, not confirmed lesions.'}, ...
    'Position',[25 20 310 65], ...
    'FontSize',10, ...
    'FontColor',MUTED, ...
    'WordWrap','on');

%% ========================================================================
% EXPLAINABILITY PAGE
% ========================================================================

makePageTitle( ...
    explainPage, ...
    'EXPLAINABILITY', ...
    'Visual explanation of the model prediction using Grad-CAM.');

explainBack = makeBackButton(explainPage,@showDashboard);

explainOriginalCard = makeCard( ...
    explainPage, ...
    [25 340 500 320], ...
    'ORIGINAL FUNDUS');

explainOriginalAxes = uiaxes( ...
    explainOriginalCard, ...
    'Position',[15 15 470 270]);

explainOriginalAxes.XTick = [];
explainOriginalAxes.YTick = [];

try
    explainOriginalAxes.Toolbar.Visible = 'off';
catch
end

explainCAMCard = makeCard( ...
    explainPage, ...
    [545 340 570 320], ...
    'GRAD-CAM AI ATTENTION');

explainCAMAxes = uiaxes( ...
    explainCAMCard, ...
    'Position',[15 35 540 250]);

explainCAMAxes.XTick = [];
explainCAMAxes.YTick = [];

try
    explainCAMAxes.Toolbar.Visible = 'off';
catch
end

explainCAMSource = uilabel( ...
    explainCAMCard, ...
    'Text','Attention method: pending', ...
    'Position',[15 10 540 20], ...
    'FontSize',9, ...
    'FontWeight','bold', ...
    'FontColor',MUTED, ...
    'HorizontalAlignment','center');

explainInfoCard = makeCard( ...
    explainPage, ...
    [25 100 1090 210], ...
    'AI EXPLANATION');

explainPrediction = uilabel( ...
    explainInfoCard, ...
    'Text','Prediction: —', ...
    'Position',[25 125 500 35], ...
    'FontSize',17, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

explainConfidence = uilabel( ...
    explainInfoCard, ...
    'Text','Confidence: —', ...
    'Position',[25 85 500 30], ...
    'FontSize',14, ...
    'FontColor',TEXT);

explainDescription = uilabel( ...
    explainInfoCard, ...
    'Text','Run analysis to generate the explanation.', ...
    'Position',[25 30 1030 45], ...
    'FontSize',12, ...
    'FontColor',MUTED, ...
    'WordWrap','on');

%% ========================================================================
% SCREENING RESULT PAGE
% ========================================================================

makePageTitle( ...
    resultPage, ...
    'SCREENING RESULT', ...
    'Five-class diabetic retinopathy grading and referable DR decision.');

resultBack = makeBackButton(resultPage,@showDashboard);

resultMainCard = makeCard( ...
    resultPage, ...
    [25 395 1090 250], ...
    'FINAL AI SCREENING RESULT');

resultGradePage = uilabel( ...
    resultMainCard, ...
    'Text','GRADE —', ...
    'Position',[25 125 390 65], ...
    'FontSize',31, ...
    'FontWeight','bold', ...
    'FontColor',BLUE);

resultConfidencePage = uilabel( ...
    resultMainCard, ...
    'Text','Confidence: —', ...
    'Position',[450 145 250 35], ...
    'FontSize',16, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

resultReferablePage = uilabel( ...
    resultMainCard, ...
    'Text','Referable DR: —', ...
    'Position',[450 95 300 35], ...
    'FontSize',16, ...
    'FontWeight','bold', ...
    'FontColor',TEXT);

resultDecisionPage = uilabel( ...
    resultMainCard, ...
    'Text','AWAITING RESULT', ...
    'Position',[780 90 260 75], ...
    'FontSize',17, ...
    'FontWeight','bold', ...
    'FontColor',MUTED, ...
    'HorizontalAlignment','center');

probabilityCard = makeCard( ...
    resultPage, ...
    [25 100 520 270], ...
    'MODEL CLASS PROBABILITIES');

resultProbLabels = gobjects(5,1);

for k = 1:5

    y = 200 - (k-1)*38;

    resultProbLabels(k) = uilabel( ...
        probabilityCard, ...
        'Text',sprintf( ...
        '%s: 0.0%%', ...
        char(state.classNames(k))), ...
        'Position',[25 y 450 28], ...
        'FontSize',12, ...
        'FontColor',TEXT);

end

recommendCard = uipanel( ...
    resultPage, ...
    'Position',[570 100 545 270], ...
    'BackgroundColor',NAVY, ...
    'BorderType','none');

uilabel( ...
    recommendCard, ...
    'Text','SCREENING RECOMMENDATION', ...
    'Position',[25 210 495 30], ...
    'FontSize',18, ...
    'FontWeight','bold', ...
    'FontColor',WHITE);

resultRecommendation = uilabel( ...
    recommendCard, ...
    'Text','Complete analysis to generate recommendation.', ...
    'Position',[25 70 495 110], ...
    'FontSize',14, ...
    'FontWeight','bold', ...
    'FontColor',LIGHTBLUE, ...
    'WordWrap','on');

%% ========================================================================
% REPORT PAGE
% ========================================================================

makePageTitle( ...
    reportPage, ...
    'CLINICAL REPORT', ...
    'Generated screening summary for clinical review.');

reportBack = makeBackButton(reportPage,@showDashboard);

reportBox = uitextarea( ...
    reportPage, ...
    'Position',[25 125 1090 500], ...
    'Editable','off', ...
    'FontName','Consolas', ...
    'FontSize',12, ...
    'BackgroundColor',WHITE, ...
    'Value',{'No report generated yet.'});

saveReportButton = uibutton( ...
    reportPage, ...
    'Text','Generate & Save Report', ...
    'Position',[25 55 250 50], ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'FontColor',WHITE, ...
    'BackgroundColor',BLUE2, ...
    'ButtonPushedFcn',@generateReport);

%% ========================================================================
% INITIAL PAGE
% ========================================================================

showDashboard();

%% ========================================================================
% SIDEBAR BUTTON CREATOR
% ========================================================================

    function b = makeSideButton(parent,textValue,pos,bgColor,callback)

        b = uibutton( ...
            parent, ...
            'Text',textValue, ...
            'Position',pos, ...
            'FontSize',13, ...
            'FontWeight','bold', ...
            'FontColor',WHITE, ...
            'BackgroundColor',bgColor, ...
            'ButtonPushedFcn',callback);

    end

%% ========================================================================
% CARD CREATOR
% ========================================================================

    function p = makeCard(parent,pos,titleText)

        p = uipanel( ...
            parent, ...
            'Position',pos, ...
            'BackgroundColor',WHITE, ...
            'BorderType','line');

        uilabel( ...
            p, ...
            'Text',titleText, ...
            'Position',[15 pos(4)-42 pos(3)-30 28], ...
            'FontSize',16, ...
            'FontWeight','bold', ...
            'FontColor',TEXT, ...
            'HorizontalAlignment','center');

    end

%% ========================================================================
% PAGE TITLE
% ========================================================================

    function makePageTitle(parent,titleText,subtitleText)

        uilabel( ...
            parent, ...
            'Text',titleText, ...
            'Position',[25 690 800 45], ...
            'FontSize',25, ...
            'FontWeight','bold', ...
            'FontColor',TEXT);

        uilabel( ...
            parent, ...
            'Text',subtitleText, ...
            'Position',[25 655 900 25], ...
            'FontSize',12, ...
            'FontColor',MUTED);

    end

%% ========================================================================
% BACK BUTTON
% ========================================================================

    function b = makeBackButton(parent,callback)

        b = uibutton( ...
            parent, ...
            'Text','← Dashboard', ...
            'Position',[970 680 145 42], ...
            'FontSize',11, ...
            'FontWeight','bold', ...
            'FontColor',WHITE, ...
            'BackgroundColor',NAVY2, ...
            'ButtonPushedFcn',callback);

    end

%% ========================================================================
% PAGE NAVIGATION
% ========================================================================

    function showDashboard(~,~)

        dashboardPage.Visible = 'on';
        qualityPage.Visible = 'off';
        structurePage.Visible = 'off';
        evidencePage.Visible = 'off';
        explainPage.Visible = 'off';
        resultPage.Visible = 'off';
        reportPage.Visible = 'off';

        headerStatus.Text = '● DASHBOARD';

    end

    function openQualityPage()

        dashboardPage.Visible = 'off';
        qualityPage.Visible = 'on';
        structurePage.Visible = 'off';
        evidencePage.Visible = 'off';
        explainPage.Visible = 'off';
        resultPage.Visible = 'off';
        reportPage.Visible = 'off';

        headerStatus.Text = '● IMAGE QUALITY';

    end

    function openStructurePage()

        dashboardPage.Visible = 'off';
        qualityPage.Visible = 'off';
        structurePage.Visible = 'on';
        evidencePage.Visible = 'off';
        explainPage.Visible = 'off';
        resultPage.Visible = 'off';
        reportPage.Visible = 'off';

        headerStatus.Text = '● RETINAL STRUCTURE';

    end

    function openEvidencePage()

        dashboardPage.Visible = 'off';
        qualityPage.Visible = 'off';
        structurePage.Visible = 'off';
        evidencePage.Visible = 'on';
        explainPage.Visible = 'off';
        resultPage.Visible = 'off';
        reportPage.Visible = 'off';

        headerStatus.Text = '● CLINICAL EVIDENCE';

    end

    function openExplainPage()

        dashboardPage.Visible = 'off';
        qualityPage.Visible = 'off';
        structurePage.Visible = 'off';
        evidencePage.Visible = 'off';
        explainPage.Visible = 'on';
        resultPage.Visible = 'off';
        reportPage.Visible = 'off';

        headerStatus.Text = '● EXPLAINABILITY';

    end

    function openResultPage()

        dashboardPage.Visible = 'off';
        qualityPage.Visible = 'off';
        structurePage.Visible = 'off';
        evidencePage.Visible = 'off';
        explainPage.Visible = 'off';
        resultPage.Visible = 'on';
        reportPage.Visible = 'off';

        headerStatus.Text = '● SCREENING RESULT';

    end

    function openReportPage()

        dashboardPage.Visible = 'off';
        qualityPage.Visible = 'off';
        structurePage.Visible = 'off';
        evidencePage.Visible = 'off';
        explainPage.Visible = 'off';
        resultPage.Visible = 'off';
        reportPage.Visible = 'on';

        headerStatus.Text = '● CLINICAL REPORT';

    end

%% ========================================================================
% UPLOAD
% ========================================================================

    function uploadImage(~,~)

        [file,path] = uigetfile( ...
            {'*.png;*.jpg;*.jpeg;*.tif;*.tiff','Fundus Images'; ...
             '*.*','All Files'}, ...
            'Select Retinal Fundus Image');

        if isequal(file,0)
            return;
        end

        try

            img = imread(fullfile(path,file));

            if ndims(img) == 2
                img = repmat(img,[1 1 3]);
            end

            if size(img,3) > 3
                img = img(:,:,1:3);
            end

            if ~isa(img,'uint8')
                img = im2uint8(img);
            end

            state.image = img;
            state.fileName = string(file);

            resetAnalysis();

            imshow(state.image,'Parent',originalAxes);
            axis(originalAxes,'image');

            originalAxes.XTick = [];
            originalAxes.YTick = [];

            title(originalAxes,'Original Fundus Image');

            imshow(state.image,'Parent',qualityOriginalAxes);
            axis(qualityOriginalAxes,'image');

            qualityOriginalAxes.XTick = [];
            qualityOriginalAxes.YTick = [];

            title(qualityOriginalAxes,'Original Fundus Image');

            imshow(state.image,'Parent',explainOriginalAxes);
            axis(explainOriginalAxes,'image');

            explainOriginalAxes.XTick = [];
            explainOriginalAxes.YTick = [];

            title(explainOriginalAxes,'Original Fundus Image');

            cla(enhancedAxes);
            title(enhancedAxes,'Waiting for analysis');

            cla(camAxes);
            title(camAxes,'AI attention will appear here');

            cla(structureAxes);
            title(structureAxes,'Run analysis');

            cla(evidenceAxes);
            title(evidenceAxes,'Run analysis');

            cla(explainCAMAxes);
            title(explainCAMAxes,'Run analysis');

            statusLabel.Text = '● IMAGE LOADED';
            statusLabel.FontColor = BLUE;

            headerStatus.Text = '● IMAGE LOADED';

            pipelineLabel.Text = ...
                ['Image loaded: ' char(state.fileName) ...
                 ' → click Analyze Retina'];

            drawnow;

        catch ME

            uialert( ...
                fig, ...
                ['Unable to load image.' newline newline ...
                 ME.message], ...
                'Image Error');

        end

    end

%% ========================================================================
% ANALYSIS
% ========================================================================

function analyzeImage(~,~)

    if isempty(state.image)

        uialert( ...
            fig, ...
            'Please upload a fundus image first.', ...
            'No Image');

        return;
    end

    try

        %% ================================================================
        % START
        % ================================================================

        statusLabel.Text = '● ANALYZING';
        statusLabel.FontColor = ORANGE;

        headerStatus.Text = '● ANALYZING';

        pipelineLabel.Text = ...
            'Step 1/5: assessing image quality...';

        drawnow;


        %% ================================================================
        % STEP 1 — IMAGE QUALITY
        % ================================================================

        [quality,processed,info] = ...
            assessImageQualityLocal(state.image);

        state.processed = processed;

        state.qualityTotal = info.total;
        state.focusScore = info.focus;
        state.illuminationScore = info.illumination;
        state.fovScore = info.fov;
        state.contrastScore = info.contrast;
        state.qualityStatus = quality;

        updateQualityUI(quality,info);


        % Enhanced image is ONLY used for visualization and
        % retinal structure / clinical candidate analysis.

        imshow(processed,'Parent',enhancedAxes);
        axis(enhancedAxes,'image');

        enhancedAxes.XTick = [];
        enhancedAxes.YTick = [];

        title( ...
            enhancedAxes, ...
            'Enhanced Retinal View');


        imshow(processed,'Parent',qualityEnhancedAxes);
        axis(qualityEnhancedAxes,'image');

        qualityEnhancedAxes.XTick = [];
        qualityEnhancedAxes.YTick = [];

        title( ...
            qualityEnhancedAxes, ...
            'Enhanced Retinal View');


        %% ================================================================
        % STEP 2 — RETINAL STRUCTURE
        % ================================================================

        pipelineLabel.Text = ...
            'Step 2/5: analyzing retinal structures...';

        drawnow;


        state.retinaMask = ...
            createRetinaMask(state.image);


        [state.vesselMask,state.vesselDensity] = ...
            detectVessels( ...
            state.processed, ...
            state.retinaMask);


        [ ...
            state.opticDiscDetected, ...
            state.opticDiscCenter] = ...
            detectOpticDisc( ...
            state.processed, ...
            state.retinaMask);


        [ ...
            state.foveaEstimated, ...
            state.foveaCenter] = ...
            estimateFovea( ...
            state.processed, ...
            state.retinaMask, ...
            state.opticDiscCenter);


        updateStructureUI();


        %% ================================================================
        % STEP 3 — CLINICAL CANDIDATE EVIDENCE
        % ================================================================

        pipelineLabel.Text = ...
            'Step 3/5: detecting clinical candidate evidence...';

        drawnow;


        candidates = ...
            detectClinicalCandidates( ...
            state.processed, ...
            state.retinaMask);


        state.brightCandidates = candidates.bright;
        state.darkCandidates = candidates.dark;
        state.redCandidates = candidates.red;
        state.totalCandidates = candidates.total;

        state.brightMask = candidates.brightMask;
        state.darkMask = candidates.darkMask;
        state.redMask = candidates.redMask;


        updateEvidenceUI();


        %% ================================================================
        % STEP 4 — RESNET-18 CLASSIFICATION + GRAD-CAM
        % ================================================================

        pipelineLabel.Text = ...
            'Step 4/5: running ResNet-18 classification and Grad-CAM...';

        drawnow;


        if state.modelLoaded

            % ============================================================
            % IMPORTANT
            %
            % The trained ResNet-18 was trained/evaluated using ORIGINAL
            % fundus images.
            %
            % Therefore DO NOT send state.processed to the model.
            % ============================================================

            modelInputImage = state.image;


            [ ...
                grade, ...
                gradeIndex, ...
                confidence, ...
                probabilities, ...
                attention, ...
                attentionSource] = ...
                classifyWithModel( ...
                modelInputImage, ...
                state.trainedNet, ...
                state.classNames);

        else

            % ============================================================
            % FALLBACK
            % ============================================================

            [ ...
                grade, ...
                gradeIndex, ...
                confidence, ...
                probabilities, ...
                attention, ...
                attentionSource] = ...
                fallbackClassification( ...
                state.image, ...
                state.retinaMask, ...
                candidates);

        end


        %% ================================================================
        % SAVE MODEL RESULTS
        % ================================================================

        state.grade = grade;
        state.gradeIndex = gradeIndex;
        state.confidence = confidence;
        state.probabilities = probabilities;

        state.attentionMap = attention;
        state.attentionSource = attentionSource;


%% ================================================================
% REFERABLE DR DECISION
% ================================================================
%
% Grade 0 = No DR
% Grade 1 = Mild DR
% Grade 2 = Moderate DR
% Grade 3 = Severe DR
% Grade 4 = Proliferative DR
%
% The predicted DR grade is obtained directly from the ResNet-18
% class with the highest probability.
%
% For the dashboard screening decision:
% Moderate, Severe and Proliferative DR are considered referable.
%
% This keeps the displayed Grade and Referable decision consistent.

if numel(probabilities) >= 5

    % Probability of Moderate + Severe + Proliferative DR
    state.referableProbability = ...
        sum(probabilities(3:5));

else

    state.referableProbability = 0;

end


% Referral decision based on predicted DR grade

state.referable = ...
    state.gradeIndex >= 2;

        %% ================================================================
        % UPDATE RESULT PAGE
        % ================================================================

        updateResultUI();


        %% ================================================================
        % GRAD-CAM / ATTENTION MAP
        % ================================================================

        showAttention( ...
            state.image, ...
            state.attentionMap, ...
            camAxes, ...
            state.attentionSource);


        showAttention( ...
            state.image, ...
            state.attentionMap, ...
            explainCAMAxes, ...
            state.attentionSource);


        %% ================================================================
        % CLINICAL CANDIDATE MAP
        % ================================================================

        showCandidateMap( ...
            state.image, ...
            candidates, ...
            evidenceAxes);


        %% ================================================================
        % RETINAL STRUCTURE OVERLAY
        % ================================================================

        showStructureOverlay();


        %% ================================================================
        % STEP 5 — SCREENING RECOMMENDATION
        % ================================================================

        pipelineLabel.Text = ...
            'Step 5/5: preparing screening recommendation...';

        drawnow;


        updateRecommendation();


        %% ================================================================
        % UPDATE MAIN DASHBOARD
        % ================================================================

        updateDashboard();


        %% ================================================================
        % COMPLETE
        % ================================================================

        statusLabel.Text = ...
            '● SCREENING COMPLETE';

        statusLabel.FontColor = GREEN;

        headerStatus.Text = ...
            '● SCREENING COMPLETE';

        pipelineLabel.Text = ...
            'SCREENING COMPLETE: quality + structures + evidence + grading + XAI.';

        drawnow;


    catch ME

        statusLabel.Text = ...
            '● ANALYSIS ERROR';

        statusLabel.FontColor = RED;

        headerStatus.Text = ...
            '● ANALYSIS ERROR';

        pipelineLabel.Text = ...
            'Analysis stopped because an error occurred.';


        uialert( ...
            fig, ...
            ['Analysis failed:' newline newline ...
             ME.message], ...
            'Analysis Error');

    end

end
%% ========================================================================
% IMAGE QUALITY PAGE
% ========================================================================

    function showQuality(~,~)

        if isempty(state.image)

            uialert( ...
                fig, ...
                'Please upload a fundus image first.', ...
                'Image Quality');

            return;

        end

        if isempty(state.processed)

            [quality,processed,info] = ...
                assessImageQualityLocal(state.image);

            state.processed = processed;

            state.qualityTotal = info.total;
            state.focusScore = info.focus;
            state.illuminationScore = info.illumination;
            state.fovScore = info.fov;
            state.contrastScore = info.contrast;
            state.qualityStatus = quality;

            updateQualityUI(quality,info);

            imshow(processed,'Parent',qualityEnhancedAxes);
            axis(qualityEnhancedAxes,'image');

        end

        imshow(state.image,'Parent',qualityOriginalAxes);
        axis(qualityOriginalAxes,'image');

        openQualityPage();

    end

%% ========================================================================
% STRUCTURE PAGE
% ========================================================================

    function showStructure(~,~)

        if isempty(state.image)

            uialert( ...
                fig, ...
                'Please upload a fundus image first.', ...
                'Retinal Structure');

            return;

        end

        if isempty(state.retinaMask)

            uialert( ...
                fig, ...
                'Please click Analyze Retina first.', ...
                'Retinal Structure');

            return;

        end

        updateStructureUI();
        showStructureOverlay();

        openStructurePage();

    end

%% ========================================================================
% EVIDENCE PAGE
% ========================================================================

    function showEvidence(~,~)

        if isempty(state.image)

            uialert( ...
                fig, ...
                'Please upload a fundus image first.', ...
                'Clinical Evidence');

            return;

        end

        if isempty(state.brightMask)

            uialert( ...
                fig, ...
                'Please click Analyze Retina first.', ...
                'Clinical Evidence');

            return;

        end

        candidates = struct();

        candidates.brightMask = state.brightMask;
        candidates.darkMask = state.darkMask;
        candidates.redMask = state.redMask;

        showCandidateMap( ...
            state.image, ...
            candidates, ...
            evidenceAxes);

        updateEvidenceUI();

        openEvidencePage();

    end

%% ========================================================================
% EXPLAINABILITY PAGE
% ========================================================================

    function showExplainability(~,~)

        if isempty(state.image)

            uialert( ...
                fig, ...
                'Please upload a fundus image first.', ...
                'Explainability');

            return;

        end

        if isempty(state.attentionMap)

            uialert( ...
                fig, ...
                'Please click Analyze Retina first.', ...
                'Explainability');

            return;

        end

        imshow(state.image,'Parent',explainOriginalAxes);
        axis(explainOriginalAxes,'image');

        showAttention( ...
            state.image, ...
            state.attentionMap, ...
            explainCAMAxes, ...
            state.attentionSource);

        explainPrediction.Text = ...
            ['Prediction: ' char(state.grade)];

        explainConfidence.Text = ...
            sprintf( ...
            'Confidence: %.1f%%', ...
            100*state.confidence);

        explainDescription.Text = { ...
            ['The AI classified this image as ' ...
            char(state.grade) '.']; ...
            ''; ...
            ['Grad-CAM source: ' ...
            char(state.attentionSource) '.']; ...
            ''; ...
            'The highlighted regions represent model attention and are not diagnostic proof.'};

        openExplainPage();

    end

%% ========================================================================
% RESULT PAGE
% ========================================================================

    function showResult(~,~)

        if state.gradeIndex < 0

            uialert( ...
                fig, ...
                'Please click Analyze Retina first.', ...
                'Screening Result');

            return;

        end

        updateResultUI();
        openResultPage();

    end

%% ========================================================================
% REPORT PAGE
% ========================================================================

    function showReport(~,~)

        if state.gradeIndex < 0

            uialert( ...
                fig, ...
                'Please click Analyze Retina first.', ...
                'Clinical Report');

            return;

        end

        reportBox.Value = createReportText();

        openReportPage();

    end

%% ========================================================================
% GENERATE REPORT
% ========================================================================

    function generateReport(~,~)

        if state.gradeIndex < 0

            uialert( ...
                fig, ...
                'Please click Analyze Retina first.', ...
                'Clinical Report');

            return;

        end

        reportText = createReportText();

        reportBox.Value = reportText;

        timestamp = string( ...
            datetime( ...
            'now', ...
            'Format','yyyyMMdd_HHmmss'));

        reportFile = fullfile( ...
            resultsDir, ...
            "DR_Screening_Report_" + ...
            timestamp + ".txt");

        fid = fopen(reportFile,'w');

        if fid == -1

            uialert( ...
                fig, ...
                'Unable to create report file.', ...
                'Report Error');

            return;

        end

        for k = 1:numel(reportText)

            fprintf( ...
                fid, ...
                '%s\n', ...
                char(reportText{k}));

        end

        fclose(fid);

        uialert( ...
            fig, ...
            ['Report generated successfully.' newline newline ...
             reportFile], ...
            'Report Generated');

        openReportPage();

    end

%% ========================================================================
% NEW SCREENING
% ========================================================================

    function newScreening(~,~)

        resetAnalysis();

        cla(originalAxes);
        cla(enhancedAxes);
        cla(camAxes);
        cla(structureAxes);
        cla(evidenceAxes);
        cla(explainCAMAxes);

        title(originalAxes,'Upload an image');
        title(enhancedAxes,'Waiting for analysis');
        title(camAxes,'AI attention will appear here');
        title(structureAxes,'Run analysis');
        title(evidenceAxes,'Run analysis');
        title(explainCAMAxes,'Run analysis');

        showDashboard();

        statusLabel.Text = '● READY';
        statusLabel.FontColor = MUTED;

        headerStatus.Text = '● READY';

        pipelineLabel.Text = ...
            'Upload → Analyze → Review evidence → Validate AI result → Generate report';

    end

%% ========================================================================
% RESET ANALYSIS VALUES
% ========================================================================

    function resetAnalysis()

        state.processed = [];
        state.retinaMask = [];
        state.vesselMask = [];

        state.vesselDensity = 0;

        state.opticDiscDetected = false;
        state.opticDiscCenter = [];

        state.foveaEstimated = false;
        state.foveaCenter = [];

        state.qualityTotal = 0;
        state.focusScore = 0;
        state.illuminationScore = 0;
        state.fovScore = 0;
        state.contrastScore = 0;
        state.qualityStatus = "PENDING";

        state.brightCandidates = 0;
        state.darkCandidates = 0;
        state.redCandidates = 0;
        state.totalCandidates = 0;

        state.brightMask = [];
        state.darkMask = [];
        state.redMask = [];

        state.gradeIndex = -1;
        state.grade = "Not analyzed";
        state.confidence = 0;

        state.probabilities = zeros(5,1);

        state.referable = false;

        state.attentionMap = [];
        state.attentionSource = "Not generated";

        qualityOverall.Text = 'OVERALL  — / 100';
        qualityState.Text = 'PENDING';

        qualityFocus.Text = 'Focus / Sharpness: —';
        qualityIllumination.Text = 'Illumination: —';
        qualityFOV.Text = 'FOV Coverage: —';
        qualityContrast.Text = 'Contrast: —';

        brightEvidenceLabel.Text = ...
            'BRIGHT CANDIDATES: 0';

        darkEvidenceLabel.Text = ...
            'DARK CANDIDATES: 0';

        redEvidenceLabel.Text = ...
            'RED CANDIDATES: 0';

        totalEvidenceLabel.Text = ...
            'TOTAL CANDIDATES: 0';

        structureVesselLabel.Text = ...
            'Vessel Density: —';

        structureDiscLabel.Text = ...
            'Optic Disc: —';

        structureFoveaLabel.Text = ...
            'Fovea Estimate: —';

        structureFOVLabel.Text = ...
            'Retinal FOV: —';

        gradeLabel.Text = 'GRADE —';
        confidenceLabel.Text = 'CONFIDENCE: —';
        referableLabel.Text = 'REFERABLE DR: —';

        finalDecisionLabel.Text = ...
            'AWAITING ANALYSIS';

        finalDecisionLabel.FontColor = MUTED;

        resultGradePage.Text = 'GRADE —';
        resultConfidencePage.Text = 'Confidence: —';
        resultReferablePage.Text = 'Referable DR: —';
        resultDecisionPage.Text = 'AWAITING RESULT';

        resultRecommendation.Text = ...
            'Complete analysis to generate recommendation.';

        explainPrediction.Text = ...
            'Prediction: —';

        explainConfidence.Text = ...
            'Confidence: —';

        explainDescription.Text = ...
            'Run analysis to generate the explanation.';

        for k = 1:5

            resultProbLabels(k).Text = ...
                sprintf( ...
                '%s: 0.0%%', ...
                char(state.classNames(k)));

        end

    end

%% ========================================================================
% QUALITY UI
% ========================================================================

    function updateQualityUI(quality,info)

        qualityOverall.Text = ...
            sprintf( ...
            'OVERALL  %.0f / 100', ...
            info.total);

        qualityState.Text = ...
            char(quality);

        qualityFocus.Text = ...
            sprintf( ...
            'Focus / Sharpness: %.1f / 100', ...
            info.focus);

        qualityIllumination.Text = ...
            sprintf( ...
            'Illumination: %.1f / 100', ...
            info.illumination);

        qualityFOV.Text = ...
            sprintf( ...
            'FOV Coverage: %.1f / 100', ...
            info.fov);

        qualityContrast.Text = ...
            sprintf( ...
            'Contrast: %.1f / 100', ...
            info.contrast);

        qualityStatusLabel.Text = ...
            ['IMAGE QUALITY: ' char(quality)];

        if quality == "GOOD"

            qualityState.FontColor = GREEN;
            qualityStatusLabel.FontColor = GREEN;

            qualityDecisionText.Text = { ...
                'QUALITY GATE: ACCEPT'; ...
                ''; ...
                'The image meets the current prototype quality threshold.'; ...
                'Proceed with retinal analysis and clinical review.'};

        elseif quality == "BORDERLINE"

            qualityState.FontColor = ORANGE;
            qualityStatusLabel.FontColor = ORANGE;

            qualityDecisionText.Text = { ...
                'QUALITY GATE: BORDERLINE'; ...
                ''; ...
                'The image can be analyzed, but review carefully.'; ...
                'If possible, recapture with improved focus and illumination.'};

        else

            qualityState.FontColor = RED;
            qualityStatusLabel.FontColor = RED;

            qualityDecisionText.Text = { ...
                'QUALITY GATE: POOR'; ...
                ''; ...
                'The image is below the preferred screening quality threshold.'; ...
                'Recapture with better focus, illumination, contrast and FOV.'};

        end

    end

%% ========================================================================
% STRUCTURE UI
% ========================================================================

    function updateStructureUI()

        structureVesselLabel.Text = ...
            sprintf( ...
            'Vessel Density: %.2f %%', ...
            state.vesselDensity);

        if state.opticDiscDetected

            structureDiscLabel.Text = ...
                'Optic Disc: Detected';

            structureDiscLabel.FontColor = GREEN;

        else

            structureDiscLabel.Text = ...
                'Optic Disc: Not confidently detected';

            structureDiscLabel.FontColor = ORANGE;

        end

        if state.foveaEstimated

            structureFoveaLabel.Text = ...
                sprintf( ...
                'Fovea Estimate: (%.0f, %.0f)', ...
                state.foveaCenter(1), ...
                state.foveaCenter(2));

        else

            structureFoveaLabel.Text = ...
                'Fovea Estimate: Not confidently estimated';

        end

        if ~isempty(state.retinaMask) && ...
                nnz(state.retinaMask) > 0

            percent = ...
                100 * nnz(state.retinaMask) / ...
                numel(state.retinaMask);

            structureFOVLabel.Text = ...
                sprintf( ...
                'Retinal FOV: Detected (%.1f%%)', ...
                percent);

        else

            structureFOVLabel.Text = ...
                'Retinal FOV: Not detected';

        end

    end

%% ========================================================================
% STRUCTURE OVERLAY
% ========================================================================

    function showStructureOverlay()

        if isempty(state.image)
            return;
        end

        imshow(state.image,'Parent',structureAxes);

        hold(structureAxes,'on');

        if ~isempty(state.vesselMask)

            contourVessels = bwperim(state.vesselMask);

            [y,x] = find(contourVessels);

            if ~isempty(x)

                plot( ...
                    structureAxes, ...
                    x, ...
                    y, ...
                    '.', ...
                    'Color',[0.00 1.00 0.20], ...
                    'MarkerSize',1);

            end

        end

        if state.opticDiscDetected && ...
                ~isempty(state.opticDiscCenter)

            plot( ...
                structureAxes, ...
                state.opticDiscCenter(1), ...
                state.opticDiscCenter(2), ...
                'o', ...
                'Color',[1 0.8 0], ...
                'MarkerSize',12, ...
                'LineWidth',2);

        end

        if state.foveaEstimated && ...
                ~isempty(state.foveaCenter)

            plot( ...
                structureAxes, ...
                state.foveaCenter(1), ...
                state.foveaCenter(2), ...
                'x', ...
                'Color',[1 0 0], ...
                'MarkerSize',12, ...
                'LineWidth',2);

        end

        hold(structureAxes,'off');

        axis(structureAxes,'image');

        structureAxes.XTick = [];
        structureAxes.YTick = [];

        title(structureAxes,'Retinal Structure Overlay');

    end

%% ========================================================================
% EVIDENCE UI
% ========================================================================

    function updateEvidenceUI()

        brightEvidenceLabel.Text = ...
            sprintf( ...
            'BRIGHT CANDIDATES: %d', ...
            state.brightCandidates);

        darkEvidenceLabel.Text = ...
            sprintf( ...
            'DARK CANDIDATES: %d', ...
            state.darkCandidates);

        redEvidenceLabel.Text = ...
            sprintf( ...
            'RED CANDIDATES: %d', ...
            state.redCandidates);

        totalEvidenceLabel.Text = ...
            sprintf( ...
            'TOTAL CANDIDATES: %d', ...
            state.totalCandidates);

    end

%% ========================================================================
% RESULT UI
% ========================================================================

    function updateResultUI()

        gradeLabel.Text = ...
            ['GRADE ' ...
             num2str(state.gradeIndex) ...
             ' | ' ...
             char(state.grade)];

        confidenceLabel.Text = ...
            sprintf( ...
            'CONFIDENCE: %.1f%%', ...
            100*state.confidence);

        resultGradePage.Text = ...
            ['GRADE ' ...
             num2str(state.gradeIndex) ...
             ' | ' ...
             char(state.grade)];

        resultConfidencePage.Text = ...
            sprintf( ...
            'Confidence: %.1f%%', ...
            100*state.confidence);

        if state.referable

            referableLabel.Text = ...
                'REFERABLE DR: YES';

            referableLabel.FontColor = RED;

            resultReferablePage.Text = ...
                'Referable DR: YES';

            resultReferablePage.FontColor = RED;

            resultDecisionPage.Text = ...
                'REFER TO OPHTHALMOLOGY';

            resultDecisionPage.FontColor = RED;

        else

            referableLabel.Text = ...
                'REFERABLE DR: NO';

            referableLabel.FontColor = GREEN;

            resultReferablePage.Text = ...
                'Referable DR: NO';

            resultReferablePage.FontColor = GREEN;

        end

        if state.gradeIndex == 0

            gradeLabel.FontColor = GREEN;
            resultGradePage.FontColor = GREEN;

        elseif state.gradeIndex == 1

            gradeLabel.FontColor = ORANGE;
            resultGradePage.FontColor = ORANGE;

        else

            gradeLabel.FontColor = RED;
            resultGradePage.FontColor = RED;

        end

        for k = 1:5

            resultProbLabels(k).Text = ...
                sprintf( ...
                '%s: %.1f%%', ...
                char(state.classNames(k)), ...
                100*state.probabilities(k));

        end

    end

%% ========================================================================
% DASHBOARD UPDATE
% ========================================================================

    function updateDashboard()

        if state.referable

            finalDecisionLabel.Text = ...
                'REFERABLE DR SUSPECTED';

            finalDecisionLabel.FontColor = RED;

            decisionStatusLabel.Text = ...
                'DECISION: REFER';

        elseif state.gradeIndex == 1

            finalDecisionLabel.Text = ...
                'MILD DR SUSPECTED';

            finalDecisionLabel.FontColor = ORANGE;

            decisionStatusLabel.Text = ...
                'DECISION: FOLLOW-UP';

        else

            finalDecisionLabel.Text = ...
                'NON-REFERABLE DR';

            finalDecisionLabel.FontColor = GREEN;

            decisionStatusLabel.Text = ...
                'DECISION: ROUTINE';

        end

    end

%% ========================================================================
% RECOMMENDATION
% ========================================================================

    function updateRecommendation()

        recommendation = ...
            getRecommendation( ...
            state.gradeIndex, ...
            state.qualityStatus);

        resultRecommendation.Text = ...
            char(recommendation);

    end

%% ========================================================================
% QUALITY ASSESSMENT
% ========================================================================

    function [quality,processed,info] = ...
            assessImageQualityLocal(img)

        I = im2double(img);

        if ndims(I) == 2

            I = repmat(I,[1 1 3]);

        end

        if size(I,3) > 3

            I = I(:,:,1:3);

        end

        gray = rgb2gray(I);

        %% FOV

        retinaMask = gray > 0.035;

        retinaMask = imclose( ...
            retinaMask, ...
            strel('disk',8));

        retinaMask = imfill( ...
            retinaMask, ...
            'holes');

        if nnz(retinaMask) > 0

            retinaMask = ...
                bwareafilt(retinaMask,1);

        end

        fovFraction = ...
            double(nnz(retinaMask)) / ...
            double(numel(retinaMask));

        fovScore = ...
            100 * min( ...
            1, ...
            max( ...
            0, ...
            (fovFraction-0.15)/0.45));

        %% Focus

        laplacian = imfilter( ...
            gray, ...
            fspecial('laplacian',0.2), ...
            'replicate');

        focusPixels = ...
            double(laplacian(retinaMask));

        focusPixels = focusPixels(:);

        if isempty(focusPixels)

            focusRaw = 0;

        else

            focusMean = ...
                sum(focusPixels) / ...
                double(numel(focusPixels));

            centered = ...
                focusPixels - focusMean;

            focusRaw = ...
                sum(centered .* centered) / ...
                max(1,double(numel(focusPixels)-1));

        end

        focusScore = ...
            100 * normalizeLogLocal( ...
            focusRaw, ...
            1e-5, ...
            0.03);

        %% Illumination and contrast

        pixels = ...
            double(gray(retinaMask));

        pixels = pixels(:);

        if isempty(pixels)

            illuminationScore = 0;
            contrastRaw = 0;

        else

            meanBrightness = ...
                sum(pixels) / ...
                double(numel(pixels));

            brightnessScore = ...
                100 - ...
                min( ...
                100, ...
                abs(meanBrightness-0.45)*220);

            centered = ...
                pixels - meanBrightness;

            varianceValue = ...
                sum(centered .* centered) / ...
                max(1,double(numel(pixels)-1));

            variation = ...
                sqrt(max(0,varianceValue));

            uniformityScore = ...
                100 - ...
                min(100,variation*180);

            illuminationScore = ...
                0.65*brightnessScore + ...
                0.35*uniformityScore;

            contrastRaw = variation;

        end

        contrastScore = ...
            100 * min( ...
            1, ...
            max( ...
            0, ...
            (contrastRaw-0.04)/0.20));

        %% Total

        total = ...
            0.30*focusScore + ...
            0.25*illuminationScore + ...
            0.25*fovScore + ...
            0.20*contrastScore;

        total = ...
            min(100,max(0,total));

        if total >= 60

            quality = "GOOD";

        elseif total >= 45

            quality = "BORDERLINE";

        else

            quality = "POOR";

        end

        %% Enhancement

        green = I(:,:,2);

        greenCLAHE = adapthisteq( ...
            green, ...
            'NumTiles',[8 8], ...
            'ClipLimit',0.015);

        background = ...
            imgaussfilt( ...
            greenCLAHE, ...
            25);

        normalizedGreen = ...
            greenCLAHE ./ ...
            max(background,0.08);

        normalizedGreen = ...
            mat2gray(normalizedGreen);

        processed = I;

        processed(:,:,2) = normalizedGreen;

        %% Information

        info.total = total;
        info.focus = focusScore;
        info.illumination = illuminationScore;
        info.fov = fovScore;
        info.contrast = contrastScore;
        info.fovFraction = fovFraction;

    end

%% ========================================================================
% RETINAL MASK
% ========================================================================

    function mask = createRetinaMask(img)

        I = im2double(img);

        gray = rgb2gray(I);

        mask = gray > 0.035;

        mask = imclose( ...
            mask, ...
            strel('disk',10));

        mask = imfill( ...
            mask, ...
            'holes');

        if nnz(mask) > 0

            mask = bwareafilt(mask,1);

        end

        mask = imopen( ...
            mask, ...
            strel('disk',3));

    end

%% ========================================================================
% VESSEL DETECTION
% ========================================================================

    function [vesselMask,density] = ...
            detectVessels(img,retinaMask)

        I = im2double(img);

        G = I(:,:,2);

        G = adapthisteq( ...
            G, ...
            'NumTiles',[8 8], ...
            'ClipLimit',0.02);

        vesselEnhancement = ...
            imbothat( ...
            G, ...
            strel('disk',4));

        pixels = ...
            vesselEnhancement(retinaMask);

        if isempty(pixels)

            vesselMask = ...
                false(size(retinaMask));

            density = 0;

            return;

        end

        threshold = graythresh(pixels);

        vesselMask = ...
            vesselEnhancement > ...
            max(0.01,0.80*threshold);

        vesselMask = ...
            vesselMask & retinaMask;

        vesselMask = ...
            bwareaopen( ...
            vesselMask, ...
            6);

        vesselMask = ...
            imclose( ...
            vesselMask, ...
            strel('disk',1));

        density = ...
            100*nnz(vesselMask) / ...
            max(1,nnz(retinaMask));

    end

%% ========================================================================
% OPTIC DISC
% ========================================================================

    function [detected,center] = ...
            detectOpticDisc(img,retinaMask)

        I = im2double(img);

        R = I(:,:,1);
        G = I(:,:,2);

        brightness = ...
            0.65*R + ...
            0.35*G;

        candidate = ...
            brightness > 0.70 & ...
            retinaMask;

        candidate = ...
            bwareaopen(candidate,100);

        detected = false;
        center = [];

        if nnz(candidate) == 0
            return;
        end

        CC = bwconncomp(candidate);

        stats = regionprops( ...
            CC, ...
            'Area', ...
            'Eccentricity', ...
            'Centroid');

        bestArea = 0;
        bestIndex = 0;

        for k = 1:numel(stats)

            area = stats(k).Area;

            eccentricity = ...
                stats(k).Eccentricity;

            if area >= 200 && ...
                    area <= 30000 && ...
                    eccentricity < 0.90 && ...
                    area > bestArea

                bestArea = area;
                bestIndex = k;

            end

        end

        if bestIndex > 0

            detected = true;

            center = ...
                stats(bestIndex).Centroid;

        end

    end

%% ========================================================================
% FOVEA ESTIMATION
% ========================================================================

    function [estimated,center] = ...
            estimateFovea(img,retinaMask,discCenter)

        estimated = false;
        center = [];

        if isempty(discCenter) || ...
                nnz(retinaMask) == 0

            return;

        end

        [h,w,~] = size(img);

        cx = discCenter(1);
        cy = discCenter(2);

        % Prototype geometric estimate:
        % fovea is estimated temporal to the optic disc.
        offsetX = ...
            0.25 * w;

        candidateX = ...
            cx + offsetX;

        candidateY = cy;

        candidateX = ...
            min(w-1,max(1,candidateX));

        candidateY = ...
            min(h-1,max(1,candidateY));

        if retinaMask( ...
                round(candidateY), ...
                round(candidateX))

            center = ...
                [candidateX candidateY];

            estimated = true;

        end

    end

%% ========================================================================
% CLINICAL CANDIDATES
% ========================================================================

    function result = ...
            detectClinicalCandidates(img,retinaMask)

        I = im2double(img);

        R = I(:,:,1);
        G = I(:,:,2);
        B = I(:,:,3);

        %% Bright candidates

        brightMap = ...
            0.45*R + ...
            0.40*G + ...
            0.15*B;

        brightMap = ...
            adapthisteq( ...
            mat2gray(brightMap));

        brightMask = ...
            brightMap > 0.82;

        brightMask = ...
            brightMask & retinaMask;

        brightMask = ...
            bwareaopen( ...
            brightMask, ...
            15);

        %% Dark candidates

        darkBase = ...
            mat2gray( ...
            0.50*R + ...
            0.35*G + ...
            0.15*B);

        background = ...
            imgaussfilt( ...
            darkBase, ...
            9);

        darkLocal = ...
            darkBase - background;

        darkMask = ...
            darkLocal < -0.060;

        darkMask = ...
            darkMask & retinaMask;

        darkMask = ...
            bwareaopen( ...
            darkMask, ...
            5);

        %% Red candidates

        redMap = ...
            R - ...
            0.70*G - ...
            0.20*B;

        redMask = ...
            redMap > 0.12;

        redMask = ...
            redMask & retinaMask;

        redMask = ...
            bwareaopen( ...
            redMask, ...
            6);

        %% Remove optic disc from bright candidates

        [~,discCenter] = ...
            detectOpticDisc( ...
            I, ...
            retinaMask);

        if ~isempty(discCenter)

            [X,Y] = meshgrid( ...
                1:size(I,2), ...
                1:size(I,1));

            discRadius = ...
                35;

            discRegion = ...
                (X-discCenter(1)).^2 + ...
                (Y-discCenter(2)).^2 < ...
                discRadius^2;

            brightMask(discRegion) = false;

        end

        %% Count

        brightCount = ...
            countRegions(brightMask);

        darkCount = ...
            countRegions(darkMask);

        redCount = ...
            countRegions(redMask);

        result.bright = min(brightCount,999);
        result.dark = min(darkCount,999);
        result.red = min(redCount,999);

        result.total = ...
            result.bright + ...
            result.dark + ...
            result.red;

        result.brightMask = brightMask;
        result.darkMask = darkMask;
        result.redMask = redMask;

    end

%% ========================================================================
% COUNT REGIONS
% ========================================================================

    function n = countRegions(mask)

        if isempty(mask) || nnz(mask) == 0

            n = 0;

            return;

        end

        CC = bwconncomp(mask);

        n = CC.NumObjects;

    end

%% ========================================================================
% RESNET-18 CLASSIFICATION
% ========================================================================

    function [ ...
            grade, ...
            gradeIndex, ...
            confidence, ...
            probs, ...
            attention, ...
            attentionSource] = ...
            classifyWithModel(img,net,classNames)

        inputSize = [224 224 3];

        try

            if isa(net,'dlnetwork')

                inputSize = net.Layers(1).InputSize;

            end

        catch

            inputSize = [224 224 3];

        end

        if numel(inputSize) < 3

            inputSize = ...
                [inputSize(1) inputSize(2) 3];

        end

        x = imresize( ...
            img, ...
            inputSize(1:2));

        if ndims(x) == 2

            x = repmat(x,[1 1 3]);

        end

        if size(x,3) > 3

            x = x(:,:,1:3);

        end

        x = im2single(x);

        scores = predict(net,x);

        if isa(scores,'dlarray')

            scores = extractdata(scores);

        end

        scores = gather(scores);

        scores = double(scores);

        scores = squeeze(scores);

        scores = scores(:);

        if numel(scores) < 5

            error( ...
                'The trained network returned fewer than five class scores.');

        end

        scores = scores(1:5);

        if all(isfinite(scores)) && ...
                all(scores >= 0) && ...
                abs(sum(scores)-1) < 0.05

            probs = ...
                scores / ...
                max(sum(scores),eps);

        else

            scores = ...
                scores - max(scores);

            expScores = exp(scores);

            probs = ...
                expScores / ...
                max(sum(expScores),eps);

        end

        probs = ...
            double(probs(:));

        [confidence,classIndex] = ...
            max(probs);

        classIndex = ...
            max(1,min(5,classIndex));

        gradeIndex = ...
            classIndex - 1;

        grade = ...
            string(classNames(classIndex));

        %% Grad-CAM

        attentionSource = "Grad-CAM";

        try

            attention = ...
                gradCAM( ...
                net, ...
                x, ...
                classIndex, ...
                OutputUpsampling="bicubic");

            if isa(attention,'dlarray')

                attention = ...
                    extractdata(attention);

            end

            attention = gather(attention);

            attention = double(attention);

            attention = squeeze(attention);

            if isempty(attention) || ...
                    all(~isfinite(attention(:)))

                error('Invalid Grad-CAM result.');

            end

            attention(~isfinite(attention)) = 0;

            attention = mat2gray(attention);

        catch

            gray = ...
                rgb2gray(im2double(img));

            attention = ...
                mat2gray(imgradient(gray));

            attentionSource = ...
                "Gradient attention fallback";

        end

    end

%% ========================================================================
% FALLBACK
% ========================================================================

    function [ ...
            grade, ...
            gradeIndex, ...
            confidence, ...
            probs, ...
            attention, ...
            attentionSource] = ...
            fallbackClassification(img,retinaMask,candidates)

        burden = ...
            0.02*candidates.dark + ...
            0.04*candidates.red + ...
            0.03*candidates.bright;

        burden = ...
            min(1,max(0,burden));

        if burden < 0.12

            gradeIndex = 0;

        elseif burden < 0.25

            gradeIndex = 1;

        elseif burden < 0.45

            gradeIndex = 2;

        elseif burden < 0.70

            gradeIndex = 3;

        else

            gradeIndex = 4;

        end

        names = [ ...
            "No DR", ...
            "Mild DR", ...
            "Moderate DR", ...
            "Severe DR", ...
            "Proliferative DR"];

        grade = names(gradeIndex+1);

        confidence = ...
            min(0.95,0.55+abs(burden-0.5));

        probs = zeros(5,1);

        probs(gradeIndex+1) = confidence;

        remaining = ...
            (1-confidence)/4;

        for k = 1:5

            if k ~= gradeIndex+1

                probs(k) = remaining;

            end

        end

        gray = ...
            rgb2gray(im2double(img));

        attention = ...
            mat2gray(imgradient(gray));

        attention(~retinaMask) = 0;

        attentionSource = ...
            "Gradient attention fallback";

    end

%% ========================================================================
% ATTENTION VISUALIZATION
% ========================================================================

    function showAttention(img,attention,ax,source)

        cla(ax);

        if isempty(attention)

            imshow(img,'Parent',ax);

            title(ax,'Attention unavailable');

            return;

        end

        try

            base = im2double(img);

            if size(base,3) == 1

                base = repmat(base,[1 1 3]);

            end

            resizedMap = ...
                imresize( ...
                double(attention), ...
                size(base,[1 2]));

            resizedMap = ...
                mat2gray(resizedMap);

            cmap = turbo(256);

            mapIndex = ...
                max( ...
                1, ...
                min( ...
                256, ...
                round(resizedMap*255)+1));

            heat = ...
                ind2rgb( ...
                mapIndex, ...
                cmap);

            alpha = ...
                0.15 + ...
                0.60*resizedMap;

            alpha = ...
                min(0.75,max(0.15,alpha));

            alpha3 = ...
                repmat(alpha,[1 1 3]);

            blended = ...
                base .* (1-alpha3) + ...
                heat .* alpha3;

            blended = ...
                min(1,max(0,blended));

            imshow( ...
                blended, ...
                'Parent',ax);

            axis(ax,'image');

            ax.XTick = [];
            ax.YTick = [];

            title(ax,'AI Attention Map');

            camSourceLabel.Text = ...
                ['Attention status: ' char(source)];

            explainCAMSource.Text = ...
                ['Attention method: ' char(source)];

        catch

            imshow(img,'Parent',ax);

            title(ax,'Attention visualization');

        end

    end

%% ========================================================================
% CANDIDATE MAP
% ========================================================================

    function showCandidateMap(img,candidates,ax)

        cla(ax);

        imshow(img,'Parent',ax);

        hold(ax,'on');

        if isfield(candidates,'brightMask') && ...
                ~isempty(candidates.brightMask)

            contour = bwperim( ...
                candidates.brightMask);

            [y,x] = find(contour);

            if ~isempty(x)

                plot( ...
                    ax, ...
                    x, ...
                    y, ...
                    '.', ...
                    'Color',[1 0.65 0.05], ...
                    'MarkerSize',2);

            end

        end

        if isfield(candidates,'darkMask') && ...
                ~isempty(candidates.darkMask)

            contour = bwperim( ...
                candidates.darkMask);

            [y,x] = find(contour);

            if ~isempty(x)

                plot( ...
                    ax, ...
                    x, ...
                    y, ...
                    '.', ...
                    'Color',[0.10 0.40 1.00], ...
                    'MarkerSize',2);

            end

        end

        if isfield(candidates,'redMask') && ...
                ~isempty(candidates.redMask)

            contour = bwperim( ...
                candidates.redMask);

            [y,x] = find(contour);

            if ~isempty(x)

                plot( ...
                    ax, ...
                    x, ...
                    y, ...
                    '.', ...
                    'Color',[1.00 0.10 0.10], ...
                    'MarkerSize',2);

            end

        end

        hold(ax,'off');

        axis(ax,'image');

        ax.XTick = [];
        ax.YTick = [];

        title(ax,'Clinical Candidate Evidence');

    end

%% ========================================================================
% RECOMMENDATION
% ========================================================================

    function txt = ...
            getRecommendation(gradeIndex,quality)

        if quality == "POOR"

            txt = ...
                "IMAGE RECAPTURE RECOMMENDED. Improve focus, " + ...
                "illumination, contrast and retinal field of view " + ...
                "before relying on the screening result.";

            return;

        end

        switch gradeIndex

            case 0

                txt = ...
                    "No DR suspected. Routine screening follow-up " + ...
                    "is recommended, subject to clinical review.";

            case 1

                txt = ...
                    "Mild DR suspected. Clinical follow-up and " + ...
                    "ophthalmologist review are recommended.";

            case 2

                txt = ...
                    "Referable DR suspected. Ophthalmology referral " + ...
                    "is recommended.";

            case 3

                txt = ...
                    "Severe DR suspected. Prompt ophthalmology " + ...
                    "evaluation is recommended.";

            case 4

                txt = ...
                    "Proliferative DR suspected. Urgent ophthalmology " + ...
                    "evaluation is recommended.";

            otherwise

                txt = ...
                    "Clinical review recommended.";

        end

    end

%% ========================================================================
% REPORT TEXT
% ========================================================================

    function reportText = createReportText()

        timestamp = ...
            string(datetime( ...
            'now', ...
            'Format','dd MMM yyyy HH:mm:ss'));

        reportText = { ...
            '============================================================'; ...
            'EXPLAINABLE AI - DIABETIC RETINOPATHY SCREENING'; ...
            '============================================================'; ...
            ''; ...
            ['Image: ' char(state.fileName)]; ...
            ['Date : ' char(timestamp)]; ...
            ''; ...
            'SCREENING RESULT'; ...
            '------------------------------------------------------------'; ...
            ['Grade      : ' char(state.grade)]; ...
            sprintf('Confidence : %.2f %%',100*state.confidence); ...
            ['Referable DR: ' yesNo(state.referable)]; ...
            ''; ...
            'IMAGE QUALITY'; ...
            '------------------------------------------------------------'; ...
            sprintf('Overall      : %.1f / 100',state.qualityTotal); ...
            ['Status       : ' char(state.qualityStatus)]; ...
            sprintf('Focus        : %.1f / 100',state.focusScore); ...
            sprintf('Illumination : %.1f / 100',state.illuminationScore); ...
            sprintf('FOV          : %.1f / 100',state.fovScore); ...
            sprintf('Contrast     : %.1f / 100',state.contrastScore); ...
            ''; ...
            'RETINAL STRUCTURE'; ...
            '------------------------------------------------------------'; ...
            sprintf('Vessel Density : %.2f %%',state.vesselDensity); ...
            ['Optic Disc     : ' yesNo(state.opticDiscDetected)]; ...
            ['Fovea Estimate : ' yesNo(state.foveaEstimated)]; ...
            ''; ...
            'CLINICAL CANDIDATE EVIDENCE'; ...
            '------------------------------------------------------------'; ...
            sprintf('Bright Candidates : %d',state.brightCandidates); ...
            sprintf('Dark Candidates   : %d',state.darkCandidates); ...
            sprintf('Red Candidates    : %d',state.redCandidates); ...
            sprintf('Total Candidates  : %d',state.totalCandidates); ...
            ''; ...
            'CLASS PROBABILITIES'; ...
            '------------------------------------------------------------'};

        for k = 1:5

            reportText{end+1} = ...
                sprintf( ...
                '%s : %.2f %%', ...
                char(state.classNames(k)), ...
                100*state.probabilities(k));

        end

        reportText(end+1:end+7) = { ...
            ''; ...
            'EXPLAINABILITY'; ...
            '------------------------------------------------------------'; ...
            ['Attention Method : ' char(state.attentionSource)]; ...
            ''; ...
            'RECOMMENDATION'; ...
            '------------------------------------------------------------'};

        reportText{end+1} = ...
            char(getRecommendation( ...
            state.gradeIndex, ...
            state.qualityStatus));

        reportText(end+1:end+5) = { ...
            ''; ...
            'IMPORTANT'; ...
            'This is a research prototype.'; ...
            'Candidate regions are algorithmic evidence only.'; ...
            'AI output does not replace ophthalmologist examination.'};

    end

%% ========================================================================
% HELPERS
% ========================================================================

    function txt = yesNo(value)

        if value
            txt = 'Yes';
        else
            txt = 'No';
        end

    end

    function txt = ternaryText(condition,a,b)

        if condition
            txt = a;
        else
            txt = b;
        end

    end

    function out = normalizeLogLocal(value,low,high)

        value = max(value,low);

        denominator = ...
            log10(high)-log10(low);

        if denominator <= 0

            out = 0;

            return;

        end

        out = ...
            (log10(value)-log10(low)) / ...
            denominator;

        out = ...
            min(1,max(0,out));

    end

end