function DR_Explainable_AI_App
% ==============================================================
% EXPLAINABLE AI FOR DIABETIC RETINOPATHY SCREENING
% MATLAB R2026a
%
% FINAL VERSION
% - Website-style dashboard
% - Fixed sidebar
% - Scrollable main dashboard
% - Fundus image upload
% - Image quality assessment
% - DR screening
% - Clinical evidence
% - Explainability / attention map
% - Report generation
% - Reset
%
% NOTE:
% The current screening logic is a research/demo prototype.
% The trained AI model will be connected later.
% ==============================================================

clc;

%% ==============================================================
% PROJECT PATHS
% ==============================================================

appFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(appFolder);

dataFolder = fullfile(projectRoot,"data");
modelFolder = fullfile(projectRoot,"models");
resultsFolder = fullfile(projectRoot,"results");

if ~isfolder(dataFolder)
    mkdir(dataFolder);
end

if ~isfolder(modelFolder)
    mkdir(modelFolder);
end

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

%% ==============================================================
% COLORS
% ==============================================================

NAVY = [0.03 0.12 0.21];
BLUE = [0.08 0.30 0.52];
BG = [0.95 0.97 0.99];
WHITE = [1 1 1];

TEXT = [0.05 0.14 0.23];
GRAY = [0.40 0.45 0.50];

GREEN = [0.05 0.55 0.25];
RED = [0.75 0.10 0.10];
ORANGE = [0.80 0.45 0.05];

%% ==============================================================
% APPLICATION STATE
% ==============================================================

img = [];
fileName = "";

quality = "NOT ANALYZED";

focusScore = 0;
illuminationScore = 0;
fovScore = 0;
totalQuality = 0;

grade = "Not analyzed";
confidence = 0;
referable = false;

micro = 0;
hemorrhage = 0;
exudate = 0;
vesselDensity = 0;

%% ==============================================================
% MAIN WINDOW
% ==============================================================

fig = uifigure( ...
    "Name","Explainable AI - Diabetic Retinopathy Screening", ...
    "Position",[80 40 1450 900], ...
    "Color",BG);

fig.WindowState = "maximized";

%% ==============================================================
% MAIN LAYOUT
% ==============================================================

mainGrid = uigridlayout(fig,[1 2]);

mainGrid.ColumnWidth = {250,"1x"};
mainGrid.RowHeight = {"1x"};

mainGrid.Padding = [0 0 0 0];
mainGrid.ColumnSpacing = 0;

%% ==============================================================
% FIXED SIDEBAR
% ==============================================================

sidebar = uipanel(mainGrid);

sidebar.Layout.Row = 1;
sidebar.Layout.Column = 1;

sidebar.BackgroundColor = NAVY;
sidebar.BorderType = "none";

%% SIDEBAR TITLE

uilabel(sidebar, ...
    "Text","DR SCREEN AI", ...
    "Position",[25 785 200 40], ...
    "FontSize",22, ...
    "FontWeight","bold", ...
    "FontColor",WHITE, ...
    "HorizontalAlignment","center");

uilabel(sidebar, ...
    "Text","EXPLAINABLE RETINAL SCREENING", ...
    "Position",[20 755 210 25], ...
    "FontSize",9, ...
    "FontColor",[0.55 0.75 0.95], ...
    "HorizontalAlignment","center");

%% SCREENING LABEL

uilabel(sidebar, ...
    "Text","SCREENING", ...
    "Position",[30 700 190 25], ...
    "FontSize",10, ...
    "FontWeight","bold", ...
    "FontColor",[0.55 0.75 0.95]);

%% UPLOAD

uibutton(sidebar, ...
    "Text","Upload Image", ...
    "Position",[30 645 190 45], ...
    "FontSize",13, ...
    "FontWeight","bold", ...
    "FontColor",WHITE, ...
    "BackgroundColor",BLUE, ...
    "ButtonPushedFcn",@uploadImage);

%% ANALYZE

uibutton(sidebar, ...
    "Text","Analyze Retina", ...
    "Position",[30 590 190 45], ...
    "FontSize",13, ...
    "FontWeight","bold", ...
    "FontColor",WHITE, ...
    "BackgroundColor",BLUE, ...
    "ButtonPushedFcn",@analyzeImage);

%% REPORT

uibutton(sidebar, ...
    "Text","Generate Report", ...
    "Position",[30 535 190 45], ...
    "FontSize",13, ...
    "FontColor",WHITE, ...
    "BackgroundColor",BLUE, ...
    "ButtonPushedFcn",@generateReport);

%% ANALYSIS LABEL

uilabel(sidebar, ...
    "Text","ANALYSIS", ...
    "Position",[30 490 190 25], ...
    "FontSize",10, ...
    "FontWeight","bold", ...
    "FontColor",[0.55 0.75 0.95]);

%% QUALITY

uibutton(sidebar, ...
    "Text","Image Quality", ...
    "Position",[30 435 190 45], ...
    "FontSize",13, ...
    "FontColor",WHITE, ...
    "BackgroundColor",BLUE, ...
    "ButtonPushedFcn",@showQuality);

%% EXPLAINABILITY

uibutton(sidebar, ...
    "Text","Explainability", ...
    "Position",[30 380 190 45], ...
    "FontSize",13, ...
    "FontColor",WHITE, ...
    "BackgroundColor",BLUE, ...
    "ButtonPushedFcn",@showExplanation);

%% RESET

uibutton(sidebar, ...
    "Text","Reset Screening", ...
    "Position",[30 325 190 45], ...
    "FontSize",13, ...
    "FontColor",WHITE, ...
    "BackgroundColor",[0.45 0.12 0.14], ...
    "ButtonPushedFcn",@resetApp);

%% SIDEBAR FOOTER

uilabel(sidebar, ...
    "Text","RESEARCH PROTOTYPE", ...
    "Position",[30 65 190 25], ...
    "FontSize",10, ...
    "FontWeight","bold", ...
    "FontColor",[0.55 0.65 0.75], ...
    "HorizontalAlignment","center");

uilabel(sidebar, ...
    "Text","MATLAB R2026a", ...
    "Position",[30 40 190 20], ...
    "FontSize",9, ...
    "FontColor",[0.45 0.55 0.65], ...
    "HorizontalAlignment","center");

uilabel(sidebar, ...
    "Text","Rural DR Screening", ...
    "Position",[30 15 190 20], ...
    "FontSize",9, ...
    "FontColor",[0.45 0.55 0.65], ...
    "HorizontalAlignment","center");

%% ==============================================================
% RIGHT CONTENT AREA
% ==============================================================

content = uipanel(mainGrid);

content.Layout.Row = 1;
content.Layout.Column = 2;

content.BackgroundColor = BG;
content.BorderType = "none";

%% ==============================================================
% IMPORTANT SCROLLING CONTAINER
% ==============================================================

scrollGrid = uigridlayout(content,[1 1]);

scrollGrid.RowHeight = {1500};
scrollGrid.ColumnWidth = {"1x"};

scrollGrid.Padding = [0 0 0 0];
scrollGrid.RowSpacing = 0;
scrollGrid.ColumnSpacing = 0;

scrollGrid.Scrollable = "on";

%% ==============================================================
% TALL DASHBOARD
% ==============================================================

dashboard = uipanel(scrollGrid);

dashboard.Layout.Row = 1;
dashboard.Layout.Column = 1;

dashboard.BackgroundColor = BG;
dashboard.BorderType = "none";

%% ==============================================================
% HEADER
% ==============================================================

header = uipanel(dashboard, ...
    "Position",[25 1400 1100 70], ...
    "BackgroundColor",WHITE, ...
    "BorderType","none");

uilabel(header, ...
    "Text","Explainable AI for Diabetic Retinopathy Screening", ...
    "Position",[20 35 800 30], ...
    "FontSize",23, ...
    "FontWeight","bold", ...
    "FontColor",TEXT);

uilabel(header, ...
    "Text","AI-assisted retinal image analysis • lesion evidence • explainable clinical decision support", ...
    "Position",[20 8 800 25], ...
    "FontSize",11, ...
    "FontColor",GRAY);

statusLabel = uilabel(header, ...
    "Text","● READY FOR SCREENING", ...
    "Position",[850 25 220 25], ...
    "FontSize",11, ...
    "FontWeight","bold", ...
    "FontColor",GREEN, ...
    "HorizontalAlignment","right");

%% ==============================================================
% STATUS BAR
% ==============================================================

statusPanel = uipanel(dashboard, ...
    "Position",[25 1325 1100 55], ...
    "BackgroundColor",WHITE, ...
    "BorderType","line");

uilabel(statusPanel, ...
    "Text","System", ...
    "Position",[20 25 70 20], ...
    "FontSize",10, ...
    "FontColor",GRAY);

systemStatus = uilabel(statusPanel, ...
    "Text","READY", ...
    "Position",[20 5 200 25], ...
    "FontSize",12, ...
    "FontWeight","bold", ...
    "FontColor",GREEN);

uilabel(statusPanel, ...
    "Text","Image Quality", ...
    "Position",[300 25 100 20], ...
    "FontSize",10, ...
    "FontColor",GRAY);

qualityStatus = uilabel(statusPanel, ...
    "Text","--", ...
    "Position",[300 5 200 25], ...
    "FontSize",12, ...
    "FontWeight","bold", ...
    "FontColor",TEXT);

uilabel(statusPanel, ...
    "Text","AI Model", ...
    "Position",[580 25 100 20], ...
    "FontSize",10, ...
    "FontColor",GRAY);

modelStatus = uilabel(statusPanel, ...
    "Text","DEMO MODE", ...
    "Position",[580 5 200 25], ...
    "FontSize",12, ...
    "FontWeight","bold", ...
    "FontColor",ORANGE);

uilabel(statusPanel, ...
    "Text","Decision", ...
    "Position",[850 25 100 20], ...
    "FontSize",10, ...
    "FontColor",GRAY);

decisionStatus = uilabel(statusPanel, ...
    "Text","--", ...
    "Position",[850 5 220 25], ...
    "FontSize",12, ...
    "FontWeight","bold", ...
    "FontColor",TEXT);

%% ==============================================================
% FUNDUS IMAGE CARD
% ==============================================================

imageCard = uipanel(dashboard, ...
    "Title","Retinal Fundus Image", ...
    "Position",[25 1030 535 275], ...
    "BackgroundColor",WHITE);

imageAxes = uiaxes(imageCard, ...
    "Position",[15 15 505 220]);

imageAxes.XTick = [];
imageAxes.YTick = [];

axis(imageAxes,"off");

text(imageAxes, ...
    0.5,0.5, ...
    "UPLOAD FUNDUS IMAGE", ...
    "Units","normalized", ...
    "HorizontalAlignment","center", ...
    "FontSize",18, ...
    "Color",GRAY);

%% ==============================================================
% IMAGE QUALITY CARD
% ==============================================================

qualityCard = uipanel(dashboard, ...
    "Title","Image Quality Assessment", ...
    "Position",[580 1030 545 275], ...
    "BackgroundColor",WHITE);

uilabel(qualityCard, ...
    "Text","Overall Quality", ...
    "Position",[30 205 150 25], ...
    "FontSize",12, ...
    "FontWeight","bold", ...
    "FontColor",TEXT);

qualityLabel = uilabel(qualityCard, ...
    "Text","--", ...
    "Position",[200 205 300 25], ...
    "FontSize",14, ...
    "FontWeight","bold", ...
    "FontColor",GRAY);

uilabel(qualityCard, ...
    "Text","Focus", ...
    "Position",[30 165 150 25], ...
    "FontSize",11, ...
    "FontColor",GRAY);

focusLabel = uilabel(qualityCard, ...
    "Text","--", ...
    "Position",[200 165 300 25], ...
    "FontSize",12, ...
    "FontColor",TEXT);

uilabel(qualityCard, ...
    "Text","Illumination", ...
    "Position",[30 125 150 25], ...
    "FontSize",11, ...
    "FontColor",GRAY);

illuminationLabel = uilabel(qualityCard, ...
    "Text","--", ...
    "Position",[200 125 300 25], ...
    "FontSize",12, ...
    "FontColor",TEXT);

uilabel(qualityCard, ...
    "Text","Field of View", ...
    "Position",[30 85 150 25], ...
    "FontSize",11, ...
    "FontColor",GRAY);

fovLabel = uilabel(qualityCard, ...
    "Text","--", ...
    "Position",[200 85 300 25], ...
    "FontSize",12, ...
    "FontColor",TEXT);

qualityMessage = uilabel(qualityCard, ...
    "Text","Upload a fundus image to begin screening.", ...
    "Position",[30 25 480 40], ...
    "FontSize",11, ...
    "FontColor",GRAY, ...
    "WordWrap","on");

%% ==============================================================
% DR RESULT CARD
% ==============================================================

resultCard = uipanel(dashboard, ...
    "Title","DR Screening Result", ...
    "Position",[25 805 535 200], ...
    "BackgroundColor",WHITE);

uilabel(resultCard, ...
    "Text","International Clinical DR Scale", ...
    "Position",[25 140 485 25], ...
    "FontSize",11, ...
    "FontColor",GRAY, ...
    "HorizontalAlignment","center");

gradeLabel = uilabel(resultCard, ...
    "Text","Not analyzed", ...
    "Position",[25 90 485 40], ...
    "FontSize",21, ...
    "FontWeight","bold", ...
    "FontColor",TEXT, ...
    "HorizontalAlignment","center");

confidenceLabel = uilabel(resultCard, ...
    "Text","Confidence: --", ...
    "Position",[25 55 485 25], ...
    "FontSize",12, ...
    "FontColor",GRAY, ...
    "HorizontalAlignment","center");

referableLabel = uilabel(resultCard, ...
    "Text","Referable DR: --", ...
    "Position",[25 20 485 25], ...
    "FontSize",12, ...
    "FontWeight","bold", ...
    "FontColor",GRAY, ...
    "HorizontalAlignment","center");

%% ==============================================================
% CLINICAL EVIDENCE CARD
% ==============================================================

evidenceCard = uipanel(dashboard, ...
    "Title","Clinical Evidence", ...
    "Position",[580 805 545 200], ...
    "BackgroundColor",WHITE);

uilabel(evidenceCard, ...
    "Text","Microaneurysms", ...
    "Position",[20 125 150 25], ...
    "FontSize",10, ...
    "FontColor",GRAY, ...
    "HorizontalAlignment","center");

microLabel = uilabel(evidenceCard, ...
    "Text","0", ...
    "Position",[20 90 150 30], ...
    "FontSize",18, ...
    "FontWeight","bold", ...
    "FontColor",TEXT, ...
    "HorizontalAlignment","center");

uilabel(evidenceCard, ...
    "Text","Hemorrhages", ...
    "Position",[195 125 150 25], ...
    "FontSize",10, ...
    "FontColor",GRAY, ...
    "HorizontalAlignment","center");

hemorrhageLabel = uilabel(evidenceCard, ...
    "Text","0", ...
    "Position",[195 90 150 30], ...
    "FontSize",18, ...
    "FontWeight","bold", ...
    "FontColor",TEXT, ...
    "HorizontalAlignment","center");

uilabel(evidenceCard, ...
    "Text","Exudates", ...
    "Position",[370 125 150 25], ...
    "FontSize",10, ...
    "FontColor",GRAY, ...
    "HorizontalAlignment","center");

exudateLabel = uilabel(evidenceCard, ...
    "Text","0", ...
    "Position",[370 90 150 30], ...
    "FontSize",18, ...
    "FontWeight","bold", ...
    "FontColor",TEXT, ...
    "HorizontalAlignment","center");

uilabel(evidenceCard, ...
    "Text","Vessel Density", ...
    "Position",[105 45 150 25], ...
    "FontSize",10, ...
    "FontColor",GRAY, ...
    "HorizontalAlignment","center");

vesselLabel = uilabel(evidenceCard, ...
    "Text","0%", ...
    "Position",[105 15 150 25], ...
    "FontSize",15, ...
    "FontWeight","bold", ...
    "FontColor",TEXT, ...
    "HorizontalAlignment","center");

uilabel(evidenceCard, ...
    "Text","Optic Disc", ...
    "Position",[290 45 150 25], ...
    "FontSize",10, ...
    "FontColor",GRAY, ...
    "HorizontalAlignment","center");

discLabel = uilabel(evidenceCard, ...
    "Text","--", ...
    "Position",[290 15 150 25], ...
    "FontSize",15, ...
    "FontWeight","bold", ...
    "FontColor",TEXT, ...
    "HorizontalAlignment","center");

%% ==============================================================
% RETINAL STRUCTURE CARD
% ==============================================================

structureCard = uipanel(dashboard, ...
    "Title","Retinal Structure Analysis", ...
    "Position",[25 550 1100 230], ...
    "BackgroundColor",WHITE);

structureAxes = uiaxes(structureCard, ...
    "Position",[20 20 500 165]);

structureAxes.XTick = [];
structureAxes.YTick = [];

axis(structureAxes,"off");

text(structureAxes, ...
    0.5,0.5, ...
    "VESSEL SEGMENTATION", ...
    "Units","normalized", ...
    "HorizontalAlignment","center", ...
    "FontSize",16, ...
    "Color",GRAY);

structureText = uilabel(structureCard, ...
    "Text",{ ...
    "Retinal Structure Analysis"; ...
    ""; ...
    "• Retinal vessel segmentation"; ...
    "• Optic disc localization"; ...
    "• Foveal region assessment"; ...
    "• Vessel density estimation"; ...
    ""; ...
    "Analysis will appear after screening."}, ...
    "Position",[560 30 500 160], ...
    "FontSize",12, ...
    "FontColor",TEXT);

%% ==============================================================
% EXPLAINABILITY CARD
% ==============================================================

explainCard = uipanel(dashboard, ...
    "Title","Explainability / AI Evidence", ...
    "Position",[25 285 1100 230], ...
    "BackgroundColor",WHITE);

attentionAxes = uiaxes(explainCard, ...
    "Position",[20 20 500 165]);

attentionAxes.XTick = [];
attentionAxes.YTick = [];

axis(attentionAxes,"off");

text(attentionAxes, ...
    0.5,0.5, ...
    "ATTENTION MAP", ...
    "Units","normalized", ...
    "HorizontalAlignment","center", ...
    "FontSize",16, ...
    "Color",GRAY);

explanationText = uilabel(explainCard, ...
    "Text",{ ...
    "AI Explanation"; ...
    ""; ...
    "The attention map will show the retinal regions"; ...
    "that influence the screening result."; ...
    ""; ...
    "Clinical evidence includes lesion candidates,"; ...
    "retinal vessels and DR severity."}, ...
    "Position",[560 30 500 160], ...
    "FontSize",12, ...
    "FontColor",TEXT);

%% ==============================================================
% FINAL INFORMATION CARD
% ==============================================================

infoCard = uipanel(dashboard, ...
    "Title","Clinical Recommendation", ...
    "Position",[25 65 1100 190], ...
    "BackgroundColor",WHITE);

recommendationLabel = uilabel(infoCard, ...
    "Text",{ ...
    "Waiting for screening."; ...
    ""; ...
    "Upload a retinal fundus image and select Analyze Retina."; ...
    ""; ...
    "This system is a research prototype and does not replace"; ...
    "a qualified ophthalmologist."}, ...
    "Position",[30 30 1040 125], ...
    "FontSize",13, ...
    "FontColor",TEXT);

%% ==============================================================
% FOOTER
% ==============================================================

uilabel(dashboard, ...
    "Text","Explainable AI • Diabetic Retinopathy • Rural Screening Research Prototype", ...
    "Position",[25 15 1100 30], ...
    "FontSize",10, ...
    "FontColor",GRAY, ...
    "HorizontalAlignment","center");

%% ==============================================================
% UPLOAD IMAGE
% ==============================================================

    function uploadImage(~,~)

        [file,path] = uigetfile( ...
            {"*.jpg;*.jpeg;*.png;*.tif;*.tiff","Fundus Images"}, ...
            "Select Fundus Image");

        if isequal(file,0)
            return;
        end

        try

            selectedFile = fullfile(path,file);

            tempImage = imread(selectedFile);

            if ndims(tempImage) == 2
                tempImage = repmat(tempImage,[1 1 3]);
            end

            img = tempImage;
            fileName = file;

            imshow(img,"Parent",imageAxes);

            axis(imageAxes,"off");

            title(imageAxes,fileName, ...
                "Interpreter","none");

            statusLabel.Text = "● IMAGE LOADED";
            statusLabel.FontColor = BLUE;

            systemStatus.Text = "IMAGE LOADED";
            systemStatus.FontColor = BLUE;

            qualityMessage.Text = ...
                "Image loaded successfully. Click Analyze Retina.";

        catch ME

            uialert(fig,ME.message,"Image Error");

        end

    end

%% ==============================================================
% ANALYZE IMAGE
% ==============================================================

    function analyzeImage(~,~)

        if isempty(img)

            uialert(fig, ...
                "Please upload a fundus image first.", ...
                "No Image");

            return;

        end

        statusLabel.Text = "● ANALYZING...";
        statusLabel.FontColor = BLUE;

        systemStatus.Text = "ANALYZING";
        systemStatus.FontColor = BLUE;

        drawnow;

        %% ------------------------------------------------------
        % IMAGE QUALITY
        % -------------------------------------------------------

        gray = rgb2gray(img);

        grayDouble = im2double(gray);

        laplacianFilter = fspecial("laplacian",0.2);

        focusImage = imfilter( ...
            grayDouble, ...
            laplacianFilter);

        rawFocus = var(focusImage(:));

        focusScore = min(100,rawFocus * 5000);

        brightness = mean(grayDouble(:));

        illuminationScore = ...
            max(0,100 - abs(brightness - 0.45) * 200);

        fovScore = 90;

        totalQuality = ...
            0.40 * focusScore + ...
            0.35 * illuminationScore + ...
            0.25 * fovScore;

        if totalQuality >= 70

            quality = "GOOD";

            qualityColor = GREEN;

            qualityMessage.Text = ...
                "Image quality is acceptable for analysis.";

        elseif totalQuality >= 45

            quality = "BORDERLINE";

            qualityColor = ORANGE;

            qualityMessage.Text = ...
                "Borderline image quality. Consider recapturing.";

        else

            quality = "POOR";

            qualityColor = RED;

            qualityMessage.Text = ...
                "Poor image quality. Please recapture the fundus image.";

        end

        qualityLabel.Text = ...
            sprintf("%.0f%% - %s", ...
            totalQuality,quality);

        qualityLabel.FontColor = qualityColor;

        qualityStatus.Text = quality;

        qualityStatus.FontColor = qualityColor;

        focusLabel.Text = ...
            sprintf("%.1f",focusScore);

        illuminationLabel.Text = ...
            sprintf("%.1f",illuminationScore);

        fovLabel.Text = ...
            sprintf("%.1f",fovScore);

        %% ------------------------------------------------------
        % RETINAL MASK
        % -------------------------------------------------------

        retinaMask = grayDouble > 0.05;

        retinaMask = imfill( ...
            retinaMask, ...
            "holes");

        retinaMask = bwareaopen( ...
            retinaMask, ...
            500);

        %% ------------------------------------------------------
        % VESSEL ANALYSIS
        % -------------------------------------------------------

        greenChannel = img(:,:,2);

        greenChannel = adapthisteq( ...
            greenChannel);

        vesselImage = im2double( ...
            greenChannel);

        vesselEnhancement = imbothat( ...
            vesselImage, ...
            strel("disk",3));

        values = vesselEnhancement(retinaMask);

        if isempty(values)

            vesselThreshold = 0.1;

        else

            vesselThreshold = graythresh(values);

        end

        vesselMask = ...
            vesselEnhancement > vesselThreshold;

        vesselMask = ...
            vesselMask & retinaMask;

        vesselMask = bwareaopen( ...
            vesselMask,15);

        vesselDensity = ...
            100 * nnz(vesselMask) / ...
            max(1,nnz(retinaMask));

        vesselLabel.Text = ...
            sprintf("%.1f%%",vesselDensity);

        %% SHOW VESSELS

        cla(structureAxes);

        imshow(vesselMask, ...
            "Parent",structureAxes);

        title(structureAxes, ...
            "Retinal Vessel Segmentation");

        %% ------------------------------------------------------
        % LESION ANALYSIS
        % -------------------------------------------------------

        R = im2double(img(:,:,1));
        G = im2double(img(:,:,2));
        B = im2double(img(:,:,3));

        %% DARK LESIONS

        darkLesions = ...
            R < 0.35 & ...
            G < 0.35 & ...
            B < 0.35 & ...
            retinaMask;

        darkLesions = bwareaopen( ...
            darkLesions,5);

        lesionStats = regionprops( ...
            darkLesions, ...
            "Area");

        micro = 0;
        hemorrhage = 0;

        for k = 1:numel(lesionStats)

            areaValue = lesionStats(k).Area;

            if areaValue >= 5 && ...
                    areaValue <= 80

                micro = micro + 1;

            elseif areaValue > 80

                hemorrhage = hemorrhage + 1;

            end

        end

        %% EXUDATES

        exudateMask = ...
            R > 0.72 & ...
            G > 0.62 & ...
            B < 0.55 & ...
            retinaMask;

        exudateMask = bwareaopen( ...
            exudateMask,10);

        exudateStats = regionprops( ...
            exudateMask, ...
            "Area");

        exudate = 0;

        for k = 1:numel(exudateStats)

            if exudateStats(k).Area > 10

                exudate = exudate + 1;

            end

        end

        micro = min(micro,50);
        hemorrhage = min(hemorrhage,20);
        exudate = min(exudate,20);

        microLabel.Text = string(micro);

        hemorrhageLabel.Text = ...
            string(hemorrhage);

        exudateLabel.Text = ...
            string(exudate);

        %% ------------------------------------------------------
        % OPTIC DISC
        % -------------------------------------------------------

        brightRegion = ...
            grayDouble > 0.82 & ...
            retinaMask;

        brightRegion = bwareaopen( ...
            brightRegion,100);

        discStats = regionprops( ...
            brightRegion, ...
            "Area");

        if isempty(discStats)

            discLabel.Text = "Not detected";

        else

            discLabel.Text = "Detected";

        end

        %% ------------------------------------------------------
        % DR DEMO CLASSIFICATION
        % -------------------------------------------------------

        lesionBurden = ...
            micro + ...
            2 * hemorrhage + ...
            exudate;

        if lesionBurden < 3

            grade = "Level 0 - No DR";
            confidence = 78;
            referable = false;

        elseif lesionBurden < 8

            grade = "Level 1 - Mild DR";
            confidence = 72;
            referable = false;

        elseif lesionBurden < 15

            grade = "Level 2 - Moderate DR";
            confidence = 68;
            referable = true;

        elseif lesionBurden < 25

            grade = "Level 3 - Severe DR";
            confidence = 64;
            referable = true;

        else

            grade = "Level 4 - Proliferative DR";
            confidence = 60;
            referable = true;

        end

        %% ------------------------------------------------------
        % RESULT DISPLAY
        % -------------------------------------------------------

        gradeLabel.Text = grade;

        confidenceLabel.Text = ...
            sprintf("Confidence: %.1f%%",confidence);

        if referable

            referableLabel.Text = ...
                "Referable DR: YES";

            referableLabel.FontColor = RED;

            decisionStatus.Text = ...
                "REFERABLE";

            decisionStatus.FontColor = RED;

            recommendationLabel.Text = { ...
                "REFERABLE DR DETECTED"; ...
                ""; ...
                "The screening result indicates that ophthalmologist"; ...
                "review is recommended."; ...
                ""; ...
                "Research prototype — clinical confirmation required."};

        else

            referableLabel.Text = ...
                "Referable DR: NO";

            referableLabel.FontColor = GREEN;

            decisionStatus.Text = ...
                "NOT REFERABLE";

            decisionStatus.FontColor = GREEN;

            recommendationLabel.Text = { ...
                "NO REFERABLE DR DETECTED"; ...
                ""; ...
                "Continue routine diabetic eye screening according"; ...
                "to clinical guidelines."; ...
                ""; ...
                "Research prototype — clinical confirmation required."};

        end

        %% ------------------------------------------------------
        % ATTENTION MAP
        % -------------------------------------------------------

        edgeImage = edge( ...
            grayDouble, ...
            "Canny");

        attention = imgaussfilt( ...
            double(edgeImage),3);

        attention = mat2gray(attention);

        cla(attentionAxes);

        imshow(img, ...
            "Parent",attentionAxes);

        hold(attentionAxes,"on");

        heat = imagesc( ...
            attentionAxes, ...
            attention);

        heat.AlphaData = ...
            0.45 * attention;

        colormap(attentionAxes,jet);

        hold(attentionAxes,"off");

        title(attentionAxes, ...
            "AI Attention Regions");

        %% ------------------------------------------------------
        % EXPLANATION
        % -------------------------------------------------------

        explanationText.Text = { ...
            "AI Explanation"; ...
            ""; ...
            sprintf("Predicted severity: %s",grade); ...
            sprintf("Confidence: %.1f%%",confidence); ...
            sprintf("Microaneurysm candidates: %d",micro); ...
            sprintf("Hemorrhage candidates: %d",hemorrhage); ...
            sprintf("Exudate candidates: %d",exudate); ...
            sprintf("Vessel density: %.1f%%",vesselDensity); ...
            ""; ...
            "Research prototype — clinical review required."};

        %% ------------------------------------------------------
        % FINAL STATUS
        % -------------------------------------------------------

        statusLabel.Text = ...
            "● ANALYSIS COMPLETE";

        statusLabel.FontColor = GREEN;

        systemStatus.Text = ...
            "ANALYSIS COMPLETE";

        systemStatus.FontColor = GREEN;

    end

%% ==============================================================
% IMAGE QUALITY BUTTON
% ==============================================================

    function showQuality(~,~)

        if isempty(img)

            uialert(fig, ...
                "Please upload an image first.", ...
                "Image Quality");

            return;

        end

        uialert(fig, ...
            sprintf([ ...
            "IMAGE QUALITY ASSESSMENT\n\n" ...
            "Overall Quality: %s\n\n" ...
            "Focus Score: %s\n" ...
            "Illumination Score: %s\n" ...
            "Field of View Score: %s"], ...
            quality, ...
            focusLabel.Text, ...
            illuminationLabel.Text, ...
            fovLabel.Text), ...
            "Image Quality");

    end

%% ==============================================================
% EXPLAINABILITY BUTTON
% ==============================================================

    function showExplanation(~,~)

        if isempty(img)

            uialert(fig, ...
                "Please upload and analyze an image first.", ...
                "Explainability");

            return;

        end

        uialert(fig, ...
            sprintf([ ...
            "EXPLAINABLE AI RESULT\n\n" ...
            "DR Grade: %s\n\n" ...
            "Confidence: %.1f%%\n\n" ...
            "Microaneurysms: %d\n" ...
            "Hemorrhages: %d\n" ...
            "Exudates: %d\n" ...
            "Vessel Density: %.1f%%"], ...
            grade, ...
            confidence, ...
            micro, ...
            hemorrhage, ...
            exudate, ...
            vesselDensity), ...
            "Explainability");

    end

%% ==============================================================
% GENERATE REPORT
% ==============================================================

    function generateReport(~,~)

        if isempty(img)

            uialert(fig, ...
                "Please upload and analyze an image first.", ...
                "Report");

            return;

        end

        reportName = sprintf( ...
            "DR_Report_%s.txt", ...
            datestr(now,"yyyymmdd_HHMMSS"));

        reportPath = ...
            fullfile(resultsFolder,reportName);

        fid = fopen(reportPath,"w");

        if fid == -1

            uialert(fig, ...
                "Unable to create report file.", ...
                "Report Error");

            return;

        end

        fprintf(fid, ...
            "EXPLAINABLE AI DIABETIC RETINOPATHY REPORT\n");

        fprintf(fid, ...
            "============================================\n\n");

        fprintf(fid, ...
            "Image: %s\n",fileName);

        fprintf(fid, ...
            "Date: %s\n\n",datestr(now));

        fprintf(fid,"IMAGE QUALITY\n");
        fprintf(fid,"-------------\n");

        fprintf(fid, ...
            "Overall Quality: %s\n",quality);

        fprintf(fid, ...
            "Focus Score: %.2f\n",focusScore);

        fprintf(fid, ...
            "Illumination Score: %.2f\n",illuminationScore);

        fprintf(fid, ...
            "FOV Score: %.2f\n\n",fovScore);

        fprintf(fid,"CLINICAL EVIDENCE\n");
        fprintf(fid,"-----------------\n");

        fprintf(fid, ...
            "Microaneurysm Candidates: %d\n",micro);

        fprintf(fid, ...
            "Hemorrhage Candidates: %d\n",hemorrhage);

        fprintf(fid, ...
            "Exudate Candidates: %d\n",exudate);

        fprintf(fid, ...
            "Vessel Density: %.2f%%\n\n",vesselDensity);

        fprintf(fid,"DR SCREENING RESULT\n");
        fprintf(fid,"-------------------\n");

        fprintf(fid, ...
            "Grade: %s\n",grade);

        fprintf(fid, ...
            "Confidence: %.1f%%\n",confidence);

        if referable

            fprintf(fid, ...
                "Referable DR: YES\n\n");

        else

            fprintf(fid, ...
                "Referable DR: NO\n\n");

        end

        fprintf(fid,"DISCLAIMER\n");
        fprintf(fid,"----------\n");

        fprintf(fid, ...
            "This is a research prototype.\n");

        fprintf(fid, ...
            "It must not replace qualified ophthalmologist review.\n");

        fclose(fid);

        uialert(fig, ...
            sprintf( ...
            "Report generated successfully.\n\n%s", ...
            reportPath), ...
            "Report Generated");

    end

%% ==============================================================
% RESET
% ==============================================================

    function resetApp(~,~)

        img = [];
        fileName = "";

        quality = "NOT ANALYZED";

        focusScore = 0;
        illuminationScore = 0;
        fovScore = 0;
        totalQuality = 0;

        grade = "Not analyzed";
        confidence = 0;
        referable = false;

        micro = 0;
        hemorrhage = 0;
        exudate = 0;
        vesselDensity = 0;

        %% IMAGE

        cla(imageAxes);

        axis(imageAxes,"off");

        text(imageAxes, ...
            0.5,0.5, ...
            "UPLOAD FUNDUS IMAGE", ...
            "Units","normalized", ...
            "HorizontalAlignment","center", ...
            "FontSize",18, ...
            "Color",GRAY);

        %% QUALITY

        qualityLabel.Text = "--";
        qualityLabel.FontColor = GRAY;

        focusLabel.Text = "--";
        illuminationLabel.Text = "--";
        fovLabel.Text = "--";

        qualityMessage.Text = ...
            "Upload a fundus image to begin screening.";

        qualityStatus.Text = "--";
        qualityStatus.FontColor = TEXT;

        %% EVIDENCE

        microLabel.Text = "0";
        hemorrhageLabel.Text = "0";
        exudateLabel.Text = "0";

        vesselLabel.Text = "0%";

        discLabel.Text = "--";

        %% RESULT

        gradeLabel.Text = "Not analyzed";

        confidenceLabel.Text = ...
            "Confidence: --";

        referableLabel.Text = ...
            "Referable DR: --";

        referableLabel.FontColor = GRAY;

        decisionStatus.Text = "--";
        decisionStatus.FontColor = TEXT;

        %% STRUCTURE

        cla(structureAxes);

        axis(structureAxes,"off");

        text(structureAxes, ...
            0.5,0.5, ...
            "VESSEL SEGMENTATION", ...
            "Units","normalized", ...
            "HorizontalAlignment","center", ...
            "FontSize",16, ...
            "Color",GRAY);

        %% ATTENTION

        cla(attentionAxes);

        axis(attentionAxes,"off");

        text(attentionAxes, ...
            0.5,0.5, ...
            "ATTENTION MAP", ...
            "Units","normalized", ...
            "HorizontalAlignment","center", ...
            "FontSize",16, ...
            "Color",GRAY);

        %% EXPLANATION

        explanationText.Text = { ...
            "AI Explanation"; ...
            ""; ...
            "The attention map will show the retinal regions"; ...
            "that influence the screening result."; ...
            ""; ...
            "Clinical evidence includes lesion candidates,"; ...
            "retinal vessels and DR severity."};

        %% RECOMMENDATION

        recommendationLabel.Text = { ...
            "Waiting for screening."; ...
            ""; ...
            "Upload a retinal fundus image and select Analyze Retina."; ...
            ""; ...
            "This system is a research prototype and does not replace"; ...
            "a qualified ophthalmologist."};

        %% STATUS

        statusLabel.Text = ...
            "● READY FOR SCREENING";

        statusLabel.FontColor = GREEN;

        systemStatus.Text = "READY";
        systemStatus.FontColor = GREEN;

    end

end