%% DR Screening - Simulink Workflow
% Explainable AI for Diabetic Retinopathy Screening
% MATLAB R2026a

clc;

model = 'DR_Screening_Simulink';

%% Create fresh model
if bdIsLoaded(model)
    close_system(model,0);
end

if exist([model '.slx'],'file')
    delete([model '.slx']);
end

new_system(model);
open_system(model);

%% Simulation settings
set_param(model, ...
    'StopTime','100', ...
    'Solver','FixedStepDiscrete', ...
    'FixedStep','1');

%% ============================================================
% 1. IMAGE ACQUISITION
% =============================================================

add_block('simulink/Sources/Constant', ...
    [model '/Image Acquisition Rate'], ...
    'Value','10', ...
    'Position',[40 80 180 120]);

add_block('simulink/Math Operations/Gain', ...
    [model '/Image Size MB'], ...
    'Gain','2', ...
    'Position',[230 80 360 120]);

add_block('simulink/Math Operations/Product', ...
    [model '/Bandwidth Required'], ...
    'Position',[420 80 550 120]);

add_block('simulink/Sinks/Display', ...
    [model '/Bandwidth Display'], ...
    'Position',[610 75 720 125]);

%% ============================================================
% 2. IMAGE QUALITY
% =============================================================

add_block('simulink/Sources/Constant', ...
    [model '/Quality Score'], ...
    'Value','0.92', ...
    'Position',[40 190 180 230]);

add_block('simulink/Math Operations/Gain', ...
    [model '/Quality Threshold'], ...
    'Gain','1', ...
    'Position',[230 190 360 230]);

add_block('simulink/Sinks/Display', ...
    [model '/Quality Display'], ...
    'Position',[420 185 530 235]);

%% ============================================================
% 3. AI PROCESSING THROUGHPUT
% =============================================================

add_block('simulink/Sources/Constant', ...
    [model '/Processing Time sec'], ...
    'Value','4', ...
    'Position',[40 300 180 340]);

add_block('simulink/Math Operations/Math Function', ...
    [model '/Images Per Second'], ...
    'Operator','reciprocal', ...
    'Position',[230 300 360 340]);

add_block('simulink/Sinks/Display', ...
    [model '/Processing Throughput'], ...
    'Position',[420 295 550 345]);

%% ============================================================
% 4. HUMAN REVIEW CAPACITY
% =============================================================

add_block('simulink/Sources/Constant', ...
    [model '/Review Time sec'], ...
    'Value','30', ...
    'Position',[40 410 180 450]);

add_block('simulink/Math Operations/Math Function', ...
    [model '/Reviews Per Second'], ...
    'Operator','reciprocal', ...
    'Position',[230 410 360 450]);

add_block('simulink/Math Operations/Gain', ...
    [model '/Reviews Per Hour'], ...
    'Gain','3600', ...
    'Position',[420 410 550 450]);

add_block('simulink/Sinks/Display', ...
    [model '/Review Capacity'], ...
    'Position',[610 405 720 455]);

%% ============================================================
% 5. ANNUAL SCREENING REQUIREMENT
% =============================================================

add_block('simulink/Sources/Constant', ...
    [model '/Target Patients Year'], ...
    'Value','100000', ...
    'Position',[40 520 180 560]);

add_block('simulink/Math Operations/Gain', ...
    [model '/Seconds Per Year'], ...
    'Gain','31536000', ...
    'Position',[230 520 360 560]);

add_block('simulink/Math Operations/Divide', ...
    [model '/Required Average Rate'], ...
    'Position',[420 520 550 560]);

add_block('simulink/Sinks/Display', ...
    [model '/Annual Rate Display'], ...
    'Position',[610 515 720 565]);

%% ============================================================
% CONNECTIONS
% =============================================================

% Bandwidth = acquisition rate x image size
add_line(model,'Image Acquisition Rate/1','Bandwidth Required/1');
add_line(model,'Image Size MB/1','Bandwidth Required/2');
add_line(model,'Bandwidth Required/1','Bandwidth Display/1');

% Image quality
add_line(model,'Quality Score/1','Quality Threshold/1');
add_line(model,'Quality Threshold/1','Quality Display/1');

% Processing throughput
add_line(model,'Processing Time sec/1','Images Per Second/1');
add_line(model,'Images Per Second/1','Processing Throughput/1');

% Human review
add_line(model,'Review Time sec/1','Reviews Per Second/1');
add_line(model,'Reviews Per Second/1','Reviews Per Hour/1');
add_line(model,'Reviews Per Hour/1','Review Capacity/1');

% Annual requirement
add_line(model,'Target Patients Year/1','Required Average Rate/1');
add_line(model,'Seconds Per Year/1','Required Average Rate/2');
add_line(model,'Required Average Rate/1','Annual Rate Display/1');

%% ============================================================
% ANNOTATIONS
% =============================================================

add_block('built-in/Note', ...
    [model '/Title'], ...
    'Position',[40 15 750 55]);

set_param([model '/Title'], ...
    'Text','EXPLAINABLE AI - DIABETIC RETINOPATHY SCREENING WORKFLOW');

add_block('built-in/Note', ...
    [model '/FlowNote'], ...
    'Position',[780 80 1100 180]);

set_param([model '/FlowNote'], ...
    'Text',['SYSTEM FLOW\n' ...
            'Image Acquisition\n' ...
            '       ↓\n' ...
            'Image Quality Assessment\n' ...
            '       ↓\n' ...
            'AI Processing\n' ...
            '       ↓\n' ...
            'Explainability / Grad-CAM\n' ...
            '       ↓\n' ...
            'Human Clinical Review\n' ...
            '       ↓\n' ...
            'Clinical Report']);

add_block('built-in/Note', ...
    [model '/PerformanceNote'], ...
    'Position',[780 220 1100 430]);

set_param([model '/PerformanceNote'], ...
    'Text',['PERFORMANCE PARAMETERS\n\n' ...
            'Acquisition: 10 images/sec\n' ...
            'Image size: 2 MB\n' ...
            'Processing time: 4 sec/image\n' ...
            'Human review: 30 sec/case\n' ...
            'Annual target: 100,000 patients\n\n' ...
            'The model evaluates bandwidth,\n' ...
            'AI throughput and review capacity.']);

%% Save
save_system(model);

open_system(model);

disp('==========================================');
disp('DR Simulink workflow created successfully.');
disp('Model: DR_Screening_Simulink.slx');
disp('==========================================');